klacht_beschrijvingen_1 = {
    "Verstoorde darmflora": "Onevenwicht in de darmbacteriën, wat spijsverteringsproblemen en verminderde weerstand kan veroorzaken.",
    "Schimmelinfecties": "Overgroei van schimmels, vaak Candida, die huid, slijmvliezen of darmen kunnen aantasten.",
    "Darmparasieten": "Infectie van de darmen door parasitaire organismen zoals wormen of protozoa.",
    "Herstel balans darmflora na antibioticakuur": "Ondersteuning van het herstel van gezonde darmbacteriën na verstoring door antibiotica.",
    "Herstel balans darmflora bij diëten en vasten": "Stimuleren van een gezonde darmflora tijdens of na veranderingen in dieet of periodes van vasten.",
    "Slechte spijsvertering": "Verminderde vertering van voedsel, wat kan leiden tot klachten zoals een opgeblazen gevoel, misselijkheid of obstipatie.",
    "Buikpijn": "Pijn of krampen in de buikstreek, veroorzaakt door uiteenlopende spijsverteringsproblemen.",
    "Opgeblazen gevoel": "Onaangename zwelling van de buik, vaak door gasvorming of vertraagde vertering.",
    "Maagzuur": "Brandend gevoel achter het borstbeen door terugvloeiend maagzuur naar de slokdarm.",
    "Bacteriële infecties": "Infecties veroorzaakt door schadelijke bacteriën, die verschillende organen en systemen kunnen aantasten.",
    "Diabetes": "Chronische stofwisselingsziekte waarbij het lichaam onvoldoende insuline aanmaakt of gebruikt, leidend tot hoge bloedsuikerspiegels.",
    "Vermoeidheid": "Een toestand van uitputting of gebrek aan energie, zowel lichamelijk als geestelijk.",
    "Aanvullen aminozuren bij sporters": "Ondersteuning bij het herstel en de spieropbouw door aanvulling van essentiële aminozuren na sportieve inspanning.",
    "Detox voor maag en darmen": "Reiniging en ondersteuning van het maag-darmstelsel om afvalstoffen te verwijderen en de spijsvertering te verbeteren.",
    "Leverproblemen": "Functioneringsstoornissen van de lever, zoals ontgiftingsproblemen of leverontsteking.",
    "Alcoholmisbruik": "Overmatig gebruik van alcohol met schadelijke gevolgen voor organen zoals lever en hersenen.",
    "Kater": "Een verzameling van lichamelijke klachten zoals hoofdpijn, misselijkheid en vermoeidheid na overmatig alcoholgebruik.",
    "Galblaasproblemen": "Stoornissen in de werking van de galblaas, zoals galstenen of ontstekingen, die de spijsvertering kunnen beïnvloeden.",
    "Anorexia": "Een eetstoornis gekenmerkt door een extreem lage voedselinname en een verstoord lichaamsbeeld.",
    "Gezwollen buik": "Toename van de buikomvang door gasophoping, vochtretentie of ontsteking.",
    "Overproductie en afbouwen borstvoeding": "Begeleiding bij het reguleren van een te hoge melkproductie en het verminderen van borstvoeding.",
    "Preventie borstontsteking": "Ondersteunende maatregelen om ontsteking van het borstweefsel tijdens borstvoeding te voorkomen.",
    "Geringe spermaproductie": "Verminderde productie van spermacellen, wat vruchtbaarheidsproblemen kan veroorzaken.",
    "Vruchtbaarheidsproblemen": "Moeilijkheden bij het tot stand brengen van een zwangerschap, zowel bij mannen als vrouwen.",
    "Impotentie": "Onvermogen om een erectie te krijgen of te behouden die voldoende is voor bevredigende seksuele activiteit.",
    "Veroudering": "Het natuurlijke proces van lichamelijke en geestelijke veranderingen door de tijd heen, vaak met afnemende vitaliteit.",
    "Overspannenheid": "Een toestand van langdurige mentale overbelasting die kan leiden tot uitputting en stressklachten.",
    "Burn-out": "Een ernstige toestand van emotionele, mentale en fysieke uitputting door langdurige overbelasting en stress.",
    "Stress": "Gevoel van spanning of druk als reactie op externe of interne prikkels.",
    "Slapeloosheid": "Moeite met inslapen, doorslapen of een verstoorde slaapkwaliteit.",
    "Traumaverwerking": "Het emotioneel en mentaal verwerken van schokkende of ingrijpende gebeurtenissen.",
    "Nervositeit": "Een toestand van innerlijke onrust en spanning, vaak gepaard met verhoogde prikkelbaarheid.",
    "Innerlijke onrust": "Een gevoel van voortdurende onrust of spanning zonder duidelijke externe oorzaak.",
    "Afkickverschijnselen": "Fysieke en psychische klachten die optreden bij het stoppen van verslavende middelen.",
    "Prikkelbaarheid": "Verhoogde gevoeligheid voor irritatie of frustratie.",
    "Geheugenzwakte": "Verminderd vermogen om informatie op te slaan of terug te halen uit het geheugen.",
    "Adhd": "Een aandoening die gekenmerkt wordt door aandachtsproblemen, hyperactiviteit en impulsiviteit.",
    "Leerproblemen": "Moeilijkheden bij het opnemen, verwerken of toepassen van informatie, vaak zichtbaar op school of werk.",
    "Concentratiestoornissen": "Verminderde capaciteit om aandachtig te blijven bij taken of activiteiten.",
    "Dementie": "Progressieve achteruitgang van cognitieve functies zoals geheugen, denken en redeneren.",
    "Epilepsie": "Een neurologische aandoening waarbij herhaalde epileptische aanvallen optreden door abnormale hersenactiviteit.",
    "Broze haren": "Haar dat snel breekt of splijt, vaak als gevolg van beschadiging of voedingstekorten.",
    "Zwakke nagels": "Nagels die gemakkelijk breken, splijten of scheuren door zwakte of slechte voeding.",
    "Jeugdpuistjes": "Ontstekingen van de huidporiën door overmatige talgproductie, meestal bij adolescenten.",
    "Acne": "Chronische huidaandoening waarbij talgklieren verstopt en ontstoken raken, vaak gepaard met puistjes.",
    "Steenpuisten": "Diepe, pijnlijke infecties van haarzakjes of talgklieren, veroorzaakt door bacteriën.",
    "Droge huid": "Huid die trekkerig, schilferig of ruw aanvoelt door gebrek aan vocht of olie.",
    "Ruwe huid": "Ongelijkmatige, schilferige of geïrriteerde huidstructuur.",
    "Haaruitval na bevalling": "Verlies van haar als gevolg van hormonale veranderingen na zwangerschap.",
    "Diarree": "Frequent waterige ontlasting, vaak veroorzaakt door infecties, voedselintolerantie of stress.",
    "Vermoeide ogen": "Een gevoel van zwaarte, irritatie of wazig zien door langdurig gebruik van de ogen.",
    "Tranende ogen": "Overmatige productie van tranen, vaak als reactie op irritatie of ontsteking.",
    "Nachtblindheid": "Moeite om te zien bij weinig licht, vaak veroorzaakt door vitamine A-tekort.",
    "Huidveroudering": "Natuurlijke afname van elasticiteit en stevigheid van de huid met het ouder worden.",
    "Rimpels": "Fijne lijntjes en plooien in de huid, ontstaan door veroudering of externe schade zoals zonlicht.",
    "Zwangerschapsstriemen": "Streepvormige huidbeschadigingen die ontstaan door snelle groei tijdens zwangerschap.",
    "Eczeem": "Chronische ontstekingsaandoening van de huid, met jeuk, roodheid en soms schilfering.",
    "Psoriasis": "Chronische huidaandoening waarbij huidcellen zich te snel vernieuwen, leidend tot schilferige plekken.",
    "Premenstrueel syndroom": "Verschillende lichamelijke en emotionele klachten die optreden in de dagen voor de menstruatie.",
    "Luier­eczeem": "Huidontsteking in het luiergebied bij baby's, veroorzaakt door vocht, wrijving en irriterende stoffen.",
    "Dauwworm": "Een vorm van eczeem bij jonge kinderen met rode, jeukende en vochtige huiduitslag.",
    "Gewrichtsslijtage": "Afbouw van het kraakbeen in de gewrichten, wat pijn en bewegingsbeperking veroorzaakt.",
    "Reuma": "Chronische ontstekingsziekte van de gewrichten die leidt tot pijn, zwelling en verminderde mobiliteit.",
    "Artrose": "Slijtage van het gewrichtskraakbeen, leidend tot pijn en stijfheid in de gewrichten.",
    "Jicht": "Een vorm van ontstekingsreuma veroorzaakt door ophoping van urinezuurkristallen in de gewrichten.",
    "Colitis ulcerosa": "Chronische ontstekingsziekte van de dikke darm, gekenmerkt door zweren en bloederige diarree.",
    "Ziekte van crohn": "Chronische ontstekingsziekte die elk deel van het spijsverteringskanaal kan aantasten.",
    "Slijmbeursontsteking": "Ontsteking van een slijmbeurs, meestal bij gewrichten zoals schouder, elleboog of heup.",
    "Carpaal tunnel syndroom": "Beknelling van de middelste zenuw in de pols, leidend tot tintelingen, pijn en zwakte in de hand.",
    "Hielspoor": "Pijnlijke verkalking onder het hielbot, vaak veroorzaakt door overbelasting van de peesplaat.",
    "Fibromyalgie": "Chronisch pijnsyndroom gekenmerkt door spierpijn, vermoeidheid en slaapstoornissen.",
    "Haaruitval": "Overmatig verlies van hoofdhaar, veroorzaakt door genetische, hormonale of externe factoren.",
    "Afgesleten kraakbeen": "Verminderde kraakbeenlaag in gewrichten, wat leidt tot pijn en beperkte beweeglijkheid.",
    "Mee-eters": "Verstopte huidporiën gevuld met talg en dode huidcellen, zichtbaar als zwarte of witte puntjes.",
    "Bloedarmoede": "Een tekort aan rode bloedcellen of hemoglobine, leidend tot vermoeidheid en zwakte.",
    "Verstuiking": "Overrekking of scheuring van banden rond een gewricht, vaak gepaard met zwelling en pijn.",
    "Kneuzingen": "Beschadiging van weefsel onder de huid zonder open wond, zichtbaar als blauwe plekken.",
    "Voorhoofdsholte ontsteking": "Ontsteking van de sinusholtes boven de ogen, leidend tot drukpijn en verstopte neus.",
    "Sinusitis": "Ontsteking van de bijholten, vaak veroorzaakt door infecties, met symptomen als hoofdpijn en verstopte neus.",
    "Keelontsteking": "Ontsteking van het slijmvlies in de keel, vaak veroorzaakt door een virus of bacterie.",
    "Amandelontsteking": "Ontsteking van de keelamandelen, gekenmerkt door keelpijn, koorts en slikproblemen.",
    "Luchtweginfecties": "Infecties van de luchtwegen zoals verkoudheid, bronchitis of longontsteking.",
    "Vaginitis": "Ontsteking van de vagina, vaak gepaard met jeuk, afscheiding en irritatie.",
    "Herpes simplex": "Virusinfectie die blaasjes veroorzaakt op huid en slijmvliezen, vooral rond mond of genitaliën.",
    "Griep": "Virale infectie met plotselinge koorts, spierpijn, vermoeidheid en luchtwegklachten.",
    "Verkoudheid": "Milde virale infectie van de bovenste luchtwegen met symptomen zoals loopneus en keelpijn.",
    "Koortsblaasjes": "Pijnlijke blaasjes rond de lippen veroorzaakt door een herpes simplex-virusinfectie.",
    "Aften": "Pijnlijke, kleine zweertjes in de mond die het eten en spreken kunnen bemoeilijken.",
    "Verminderde weerstand": "Een verzwakt immuunsysteem waardoor infecties en ziekten sneller optreden.",
    "Ontstekingen": "Reactie van het lichaam op beschadiging of infectie, vaak gepaard met roodheid, zwelling en pijn.",
    "Gewrichtsontstekingen": "Ontstekingsreacties in de gewrichten die pijn, zwelling en stijfheid veroorzaken.",
    "Ontgifting na antibioticakuur": "Ondersteuning van het lichaam bij het verwijderen van afvalstoffen na antibiotica-gebruik.",
    "Ziekte van lyme": "Bacteriële infectie veroorzaakt door tekenbeten, met symptomen als huiduitslag, koorts en gewrichtspijn.",
    "Blaasontsteking": "Infectie van de blaas, gekenmerkt door frequent urineren en branderig gevoel bij het plassen.",
    "Urineweginfectie": "Infectie van de urinewegen zoals blaas, urineleiders of nieren, vaak gepaard met pijn en frequent urineren.",
    "Vaak urineren": "Toegenomen aandrang om te plassen, vaak een symptoom van infecties of andere aandoeningen.",
    "Weinig urineren": "Verminderde urineproductie, mogelijk veroorzaakt door uitdroging of nierproblemen.",
    "Branderig gevoel bij het plassen": "Pijn of branderigheid tijdens het urineren, vaak een teken van een urineweginfectie.",
    "Sterk geurende urine": "Ongebruikelijk sterke geur van urine, vaak veroorzaakt door infecties of dieetveranderingen.",
    "Galstenen (preventie)": "Voorkomen van de vorming van verharde afzettingen van gal in de galblaas.",
    "Leverbeschadiging": "Schade aan levercellen, vaak veroorzaakt door toxines, alcohol of infecties.",
    "Alcoholgebruik": "Consumptie van alcoholhoudende dranken, met mogelijke negatieve gevolgen voor de gezondheid bij overmatig gebruik.",
    "Medicijngebruik": "Inname van farmaceutische middelen, waarbij sommige medicijnen bijwerkingen of orgaanschade kunnen veroorzaken.",
    "Te hoog cholesterol": "Verhoogde niveaus van cholesterol in het bloed, wat het risico op hart- en vaatziekten verhoogt.",
    "Candida": "Schimmelinfectie veroorzaakt door een overgroei van de Candida-gist, vaak in mond, darmen of vagina.",
    "Witte vloed": "Witte vaginale afscheiding, normaal of als symptoom van een infectie afhankelijk van de samenstelling.",
    "Gewrichtspijn": "Pijn in één of meerdere gewrichten, veroorzaakt door ontsteking, slijtage of verwonding.",
    "Seksueel onvermogen": "Moeilijkheden bij het bereiken of behouden van seksuele prestaties of bevrediging.",
    "Libido opwekkend": "Bevordering van het seksuele verlangen en interesse.",
    "Depressiviteit": "Aanhoudende gevoelens van neerslachtigheid, verlies van interesse en verminderde energie.",
    "Zenuwzwakte": "Verzwakking van de zenuwfunctie, leidend tot gevoelsstoornissen of bewegingsproblemen.",
    "Frigiditeit": "Verminderd of afwezig seksueel verlangen of respons, vaak bij vrouwen.",
    "Impetigo": "Besmettelijke huidinfectie, vaak veroorzaakt door bacteriën, die blaasjes en korstjes veroorzaakt.",
    "Artritis": "Ontsteking van één of meerdere gewrichten, gekenmerkt door pijn, zwelling en bewegingsbeperking.",
    "Ischias": "Pijn die uitstraalt vanuit de onderrug naar het been door irritatie of beknelling van de heupzenuw.",
    "Peesontstekingen": "Ontsteking van een pees, vaak door overbelasting of blessure, met pijn en zwelling als gevolg.",
    "Tennisarm": "Ontsteking of irritatie van de pezen in de onderarm door overbelasting, resulterend in pijn rond de elleboog.",
    "Infecties": "Het binnendringen en vermenigvuldigen van ziekteverwekkers zoals bacteriën, virussen of schimmels in het lichaam.",
    "Preventie van winterziekten": "Ondersteuning van het immuunsysteem om infecties zoals griep en verkoudheid in de winter te voorkomen.",
    "Gebrek aan eetlust": "Verminderde zin om te eten, vaak als gevolg van ziekte, stress of spijsverteringsproblemen.",
    "Gewichtstoename": "Toename van lichaamsgewicht door een positieve energiebalans of onderliggende medische oorzaken.",
    "Bodybuilding": "Activiteit gericht op spieropbouw en lichaamsversterking door krachttraining en voeding.",
    "Sporters": "Personen die intensief fysiek actief zijn en specifieke ondersteuning nodig kunnen hebben voor herstel en prestaties.",
    "Borstgroei": "Toename van borstweefsel, natuurlijk bij puberteit of zwangerschap, soms hormonaal beïnvloed.",
    "Borstvoeding stimuleren": "Bevorderen van de melkproductie bij moeders die borstvoeding geven.",
    "Afslankkuren": "Diëten of methoden gericht op gewichtsverlies door verminderde calorie-inname of verhoogde vetverbranding.",
    "Overgewicht": "Te hoog lichaamsgewicht in verhouding tot lengte, wat gezondheidsrisico’s kan verhogen.",
    "Zwaarlijvigheid": "Ernstige vorm van overgewicht (obesitas), geassocieerd met verhoogd risico op chronische ziekten.",
    "Trek in zoetigheid": "Verhoogde behoefte aan suikerhoudende voedingsmiddelen, vaak gekoppeld aan bloedsuikerschommelingen.",
    "Snoep": "Consumptie van suikerhoudende snacks, vaak in verband met verhoogde energiebehoefte of emotioneel eten.",
    "Cellulitis": "Ophoping van vet onder de huid, resulterend in een bobbelige of sinaasappelhuidstructuur.",
    "Misselijkheid": "Onaangenaam gevoel in de maag dat kan leiden tot de neiging om over te geven.",
    "Overgeven": "Acutie lege maken van de maaginhoud via de mond, vaak als reactie op irritatie of ziekte.",
    "Reisziekte": "Misselijkheid en duizeligheid veroorzaakt door bewegingsconflicten tijdens reizen per auto, boot of vliegtuig.",
    "Zwangerschapsbraken": "Misselijkheid en braken tijdens de vroege zwangerschap, vaak veroorzaakt door hormonale veranderingen.",
    "Hoofdpijn": "Pijn of drukgevoel in het hoofdgebied, variërend van mild tot ernstig.",
    "Migraine": "Ernstige, vaak eenzijdige hoofdpijn, gepaard met misselijkheid, lichtgevoeligheid en soms aura's.",
    "Geheugenproblemen": "Moeite met het onthouden of terughalen van informatie, variërend van mild tot ernstig.",
    "Concentratieverlies": "Verminderde aandachtsspanne en moeite om gefocust te blijven op taken.",
    "Koude handen en voeten": "Verminderde bloedcirculatie of lage lichaamstemperatuur, leidend tot koude extremiteiten.",
    "Ouderdomsvergeetachtigheid": "Normale leeftijdsgebonden achteruitgang van het geheugen, vaak mild en geleidelijk.",
    "Oorsuizen (tinnitus)": "Waarneming van geluid zoals zoemen of fluiten in de oren zonder externe geluidsbron.",
    "Energietekort": "Gebrek aan fysieke of mentale energie om dagelijkse activiteiten uit te voeren.",
    "Spierpijn": "Pijn of stijfheid in de spieren na inspanning, overbelasting of blessure.",
    "Verbetering van geestelijke prestaties": "Verhoging van cognitieve functies zoals geheugen, concentratie en mentale scherpte.",
    "Inslaapproblemen": "Moeite met het in slaap vallen, vaak veroorzaakt door stress, spanning of een verstoord slaapritme.",
    "Bedplassen": "Onvrijwillig urineren tijdens de slaap, meestal bij kinderen maar soms ook bij volwassenen.",
    "Overactiviteit": "Overmatige lichamelijke of mentale activiteit, vaak gepaard met rusteloosheid en impulsiviteit.",
    "Angst": "Gevoel van nervositeit, onrust of vrees, vaak zonder directe aanleiding.",
    "Nachtmerries": "Levendige, angstaanjagende dromen die de slaap verstoren en emotionele stress veroorzaken.",
    "Depressies": "Langdurige periode van neerslachtigheid, verlies van interesse en verminderd functioneren.",
    "Spanningshoofdpijn": "Doffe, drukkende hoofdpijn veroorzaakt door stress, spierspanning of vermoeidheid.",
    "Slaapproblemen": "Algemene moeilijkheden met slapen, zoals moeite met inslapen, doorslapen of te vroeg wakker worden.",
    "Vermagering": "Onbedoeld gewichtsverlies als gevolg van ziekte, slechte voeding of verhoogde stofwisseling.",
    "Vetverbranding van vetcellen": "Proces waarbij opgeslagen vetten in het lichaam worden afgebroken voor energieverbruik.",
    "Reiniging talgklieren": "Ondersteuning bij het ontstoppen en zuiveren van talgklieren om huidproblemen te verminderen.",
    "Suikerziekte (ouderdom)": "Diabetes type 2, gekenmerkt door insulineresistentie en verhoogde bloedsuikerspiegels op latere leeftijd.",
    "Huidzuiverend": "Bevordering van een gezonde huid door het verwijderen van onzuiverheden en toxines.",
    "Bloedzuiverend": "Ondersteuning van het lichaam bij het verwijderen van afvalstoffen uit het bloed.",
    "Concentratiezwakte": "Moeite om langdurig de aandacht vast te houden op een taak of activiteit.",
    "Afslanken": "Vermindering van lichaamsgewicht en vetmassa door dieet, beweging of therapie.",
    "Osteoporose": "Aandoening waarbij de botdichtheid afneemt, waardoor botten brozer en breekbaarder worden.",
    "Botontkalking": "Verlies van mineralen uit botweefsel, wat leidt tot zwakkere botstructuren.",
    "Botbreuken": "Breuken in het bot als gevolg van trauma, osteoporose of verhoogde kwetsbaarheid.",
    "Bindweefselzwakte": "Verminderde stevigheid en elasticiteit van bindweefsel, wat kan leiden tot lichamelijke klachten.",
    "Tendinitis": "Ontsteking van een pees, vaak veroorzaakt door overbelasting of herhaalde bewegingen.",
    "Slijmbeurstonstekingen": "Ontsteking van een slijmbeurs die pijn en zwelling in de buurt van een gewricht veroorzaakt.",
    "Kalknagels": "Verdikte, verkleurde nagels veroorzaakt door een schimmelinfectie of kalkafzetting.",
    "Slaapstoornissen": "Brede groep aandoeningen die een goede slaap belemmeren, zoals slapeloosheid en slaapapneu.",
    "Overgangsklachten": "Fysieke en emotionele symptomen zoals opvliegers en stemmingswisselingen rond de menopauze.",
    "Vochthoping": "Ophoping van vocht in weefsels van het lichaam, vaak zichtbaar als zwelling.",
    "Oedeem": "Medische term voor overmatige vochtophoping in lichaamsweefsels, vaak in benen of enkels.",
    "Eliminatie van afvalstoffen": "Ondersteuning van het lichaam bij het verwijderen van opgehoopte afvalproducten via lever, nieren of huid.",
    "Dikke benen": "Zwelling of ophoping van vocht of vet in de benen, wat kan leiden tot zwaarte en ongemak.",
    "Overgewicht door het vasthouden van vocht": "Toename van lichaamsgewicht door ophoping van vocht in de weefsels.",
    "Vocht afdrijven": "Stimulering van de verwijdering van overtollig vocht uit het lichaam via de nieren.",
    "Urineweginfecties": "Infecties in de urinewegen zoals blaas, urineleiders of nieren, gepaard met pijn en vaak plassen.",
    "Dikke enkels": "Zwelling rond de enkels, vaak door vochtophoping of circulatieproblemen.",
    "Geringe urineproductie": "Verminderde hoeveelheid urine, mogelijk veroorzaakt door uitdroging of nierproblemen.",
    "Hongergevoel": "Sterk verlangen naar voedsel, soms veroorzaakt door bloedsuikerschommelingen of emotionele factoren.",
    "Snoepzucht": "Verhoogde trek in zoete voedingsmiddelen zoals snoep en chocolade.",
    "Snelle verzadiging": "Vervroegd gevoel van volheid tijdens het eten, wat kan wijzen op spijsverteringsproblemen.",
    "Obstipatie (chronisch)": "Langdurige problemen met trage of moeizame stoelgang.",
    "Trage darmwerking": "Vertraagde beweging van voedsel door de darmen, leidend tot een opgeblazen gevoel en obstipatie.",
    "Slechte stoelgang": "Onregelmatige, harde of moeilijke stoelgang, vaak gepaard met buikklachten.",
    "Opgroeiende kinderen": "Kinderen in de groeifase die extra voedingsstoffen en ondersteuning nodig hebben.",
    "Herstel na botbreuken": "Ondersteuning van het genezingsproces van gebroken botten door verbeterde mineralisatie en weefselherstel.",
    "Weerstand": "Het vermogen van het lichaam om zich te verdedigen tegen infecties en ziekten.",
    "Huidaandoeningen": "Verzameling van aandoeningen die de huid aantasten, zoals eczeem, acne of psoriasis.",
    "Allergieën": "Overmatige immuunreacties op doorgaans onschuldige stoffen zoals pollen, voedsel of huisstofmijt.",
    "Droge ogen": "Onvoldoende traanproductie of snelle verdamping van tranen, leidend tot irritatie en ongemak.",
    "Te hoog cholesterolgehalte": "Verhoogde concentraties cholesterol in het bloed, wat het risico op hart- en vaatziekten verhoogt.",
    "Hoge bloeddruk": "Verhoogde druk in de bloedvaten, wat het risico op hartziekten en beroertes verhoogt.",
    "Humeruschromie": "Verstoorde pigmentverdeling van de huid, vaak met ongelijkmatige verkleuring als gevolg.",
    "Dyslexie": "Leerstoornis gekenmerkt door moeite met lezen, spellen en soms schrijven, ondanks normale intelligentie.",
    "Dyspraxie": "Ontwikkelingsstoornis die invloed heeft op motorische vaardigheden en coördinatie.",
    "Brandend maagzuur": "Branderig gevoel in de borstkas door terugvloeiend maagzuur naar de slokdarm.",
    "Maagpijn": "Pijn in de maagstreek, veroorzaakt door irritatie, ontsteking of andere spijsverteringsproblemen.",
    "Vergroot uithoudingsvermogen": "Versterking van de fysieke capaciteit om langdurige inspanningen vol te houden.",
    "Helpt (sport) prestaties te verbeteren": "Ondersteuning van kracht, snelheid en herstel om sportieve prestaties te optimaliseren.",
    "Libido verhogen": "Stimulering van het seksuele verlangen en bevordering van seksuele energie.",
    "Erectiestoornis": "Onvermogen om een erectie te krijgen of te behouden voor bevredigende seksuele activiteit.",
    "Vruchtbaarheid (verhogend)": "Bevordering van de voortplantingscapaciteit bij mannen en vrouwen.",
    "Verstoorde hormoonbalans": "Onbalans in de productie of werking van hormonen, wat verschillende lichamelijke klachten kan veroorzaken.",
    "Te hoge bloeddruk": "Verhoogde druk in de bloedvaten, wat het risico op hartproblemen en beroertes verhoogt.",
    "Hart- en vaatziekten (preventief)": "Ondersteuning bij het voorkomen van aandoeningen aan het hart en de bloedvaten.",
    "Aderverkalking": "Opstapeling van vetten en kalk in de bloedvaten, leidend tot verminderde doorbloeding.",
    "Licht verhoogde spanningen in de bloeddruk": "Beginnende verhoging van de bloeddruk, vaak zonder duidelijke symptomen.",
    "Het in balans houden van de bloeddruk": "Ondersteuning bij het behouden van gezonde bloeddrukwaarden.",
    "Leverreiniging": "Stimulering van de leverfunctie om afvalstoffen efficiënter te verwerken en te verwijderen.",
    "Voedselvergiftiging": "Acute ziekte door consumptie van besmet voedsel, leidend tot misselijkheid, braken en diarree.",
    "Bescherming longweefsel": "Ondersteuning van de gezondheid van de longen tegen schadelijke invloeden zoals rook en infecties.",
    "Vermageringskuren": "Programma’s gericht op gewichtsverlies door dieet, lichaamsbeweging of supplementen.",
    "Vetverbrander": "Stimulering van de afbraak van vetreserves voor gebruik als energie.",
    "Overtollige kilo’s": "Opstapeling van lichaamsvet die kan leiden tot overgewicht en gezondheidsrisico's.",
    "Maag- en darmkrampen": "Plotselinge, pijnlijke samentrekkingen van maag of darmen, vaak door irritatie of spijsverteringsproblemen.",
    "Spijsverteringsstoornissen": "Verzameling van klachten zoals misselijkheid, opgeblazen gevoel en obstipatie door verstoorde vertering.",
    "Examenstress": "Gevoel van spanning en nervositeit rond examens of belangrijke toetsen.",
    "Plantenkoorts": "Seizoensgebonden allergische reactie op stuifmeel van planten, leidend tot niezen en oogirritatie (hooikoorts).",
    "Hartkloppingen": "Snelle, onregelmatige of hevige hartslagen die voelbaar zijn in de borst, keel of nek.",
    "Hart- en vaatziekten": "Aandoeningen die het hart en de bloedvaten aantasten, zoals hartaanval en beroerte.",
    "Hartritmestoornissen": "Onregelmatige hartslag, variërend van te snel, te langzaam of chaotisch ritme.",
    "Pijn op de borst": "Onaangenaam gevoel of pijn in de borststreek, mogelijk veroorzaakt door hart- of spijsverteringsproblemen.",
    "Prostaatvergroting": "Vergroting van de prostaatklier, vaak leidend tot problemen met urineren bij oudere mannen.",
    "Pijn bij het urineren": "Branderige of stekende pijn tijdens het plassen, vaak wijzend op een infectie of irritatie.",
    "Nadruppelen van urine": "Onvrijwillige lekkage van urine na het plassen door onvoldoende afsluiting van de plasbuis.",
    "Ongewenst urineverlies": "Onvrijwillige urinelozing, variërend van druppels tot volledige incontinentie.",
    "Slechte adem": "Onaangename geur uit de mond, vaak veroorzaakt door bacteriën of slechte mondhygiëne.",
    "Winderigheid": "Overmatige gasvorming in de darmen, leidend tot het laten van wind.",
    "Mondflora problemen": "Verstoring van het evenwicht van bacteriën in de mond, leidend tot problemen zoals slechte adem of tandvleesontstekingen.",
    "Doorslaapproblemen": "Moeite om de slaap de hele nacht vast te houden, resulterend in frequent wakker worden.",
    "Nachtelijk ontwaken": "Herhaaldelijk wakker worden tijdens de nacht, vaak leidend tot verminderde slaapkwaliteit.",
    "Opgehoopte toxines": "Ophoping van schadelijke stoffen in het lichaam die kan leiden tot verminderde gezondheid en klachten.",
    "Detox": "Reinigingsproces waarbij het lichaam wordt ondersteund in het verwijderen van afvalstoffen en toxines.",
    "Ontgiften van het lichaam": "Stimulatie van natuurlijke processen om schadelijke stoffen uit het lichaam te verwijderen.",
    "Gal- en nierstenen": "Vorming van verharde afzettingen in de galblaas of nieren, die pijn en obstructies kunnen veroorzaken.",
    "Voorkomen van migraine": "Ondersteuning bij het verminderen van de frequentie en ernst van migraineaanvallen.",
    "Celveroudering": "Processen waarbij cellen beschadigd raken en hun functie verliezen door onder andere oxidatieve stress.",
    "Cholesterol": "Vette stof in het bloed die nodig is voor lichaamsfuncties, maar bij teveel gezondheidsrisico's geeft.",
    "Veroudering van de huid": "Afname van elasticiteit, stevigheid en vochtgehalte van de huid door natuurlijke veroudering.",
    "Immuunsysteem (verzwakt)": "Verminderde afweer tegen ziekteverwekkers, leidend tot verhoogde gevoeligheid voor infecties.",
    "Verlagen bloeddruk": "Ondersteuning bij het bereiken en behouden van gezonde bloeddrukwaarden.",
    "Haarverlies en misselijkheid (chemokuur)": "Bijwerkingen van chemotherapie zoals haaruitval en misselijkheid.",
    "Chronische vermoeidheid (burn-out)": "Langdurige fysieke en mentale uitputting door overbelasting of stress.",
    "Bloedend tandvlees": "Symptoom van tandvleesontsteking, vaak veroorzaakt door onvoldoende mondhygiëne.",
    "Parodontitis": "Ernstige tandvleesontsteking die leidt tot aantasting van steunweefsels en verlies van tanden.",
    "Loszittende tanden": "Gevolg van verzwakt tandvlees en kaakbot, vaak door gevorderde tandvleesaandoeningen.",
    "Herstel na ziekte": "Ondersteuning van het lichamelijk en mentaal herstel na een periode van ziekte.",
    "Tintelingen in handen en voeten": "Prikkelend, doof of brandend gevoel in de extremiteiten, vaak door zenuwproblemen.",
    "Activering van het afweersysteem": "Stimulatie van het immuunsysteem om het lichaam beter te laten reageren op infecties.",
    "Stimulatie van het immuunsysteem": "Versterking van de natuurlijke afweermechanismen van het lichaam.",
    "Bestrijding bacteriën virussen en schimmels": "Ondersteuning van het lichaam bij het tegengaan van infectieuze micro-organismen.",
    "Ontstekingen (keel huidinfecties etc.)": "Behandeling en vermindering van ontstekingsreacties in keel, huid en andere weefsels.",
    "Prestatiedruk": "Stress of spanning door hoge verwachtingen in werk, studie of sport.",
    "Vermindering energie door onrust of drukke werkzaamheden": "Energiedaling als gevolg van mentale overbelasting of stressvolle activiteiten.",
    "Verminderd uithoudingsvermogen": "Afname van de capaciteit om fysieke of mentale inspanningen langdurig vol te houden.",
    "Geestelijke druk en inspanning": "Mentale belasting en stress door intensieve denk- of prestatietaken.",
    "Overbelasting van lichaam en geest": "Fysieke en psychische uitputting door langdurige belasting zonder voldoende herstel.",
    "Kortstondige stress": "Tijdelijke stressreactie op acute situaties die het lichaam kortdurend onder druk zet.",
    "Opvliegers": "Plotselinge warmte-aanvallen vaak voorkomend tijdens de overgang, soms met zweten en roodheid.",
    "Stemmingswisselingen": "Snelle veranderingen in emotionele stemming, vaak zonder duidelijke aanleiding.",

    "Nachtelijk transpireren": "Overmatig zweten tijdens de slaap, vaak veroorzaakt door hormonale veranderingen of infecties.",
    "Osteoporose (preventief)": "Ondersteuning bij het voorkomen van botontkalking door het versterken van botstructuren.",
    "Te hoge triglyceriden": "Verhoogde vetwaarden in het bloed die het risico op hart- en vaatziekten kunnen vergroten.",
    "Geestelijke vermoeidheid": "Mentale uitputting door langdurige stress, overbelasting of concentratieverlies.",
    "Verlaagd libido": "Afname van het seksuele verlangen, vaak door hormonale of psychische oorzaken.",
    "Bekkenbodeminstabiliteit": "Verminderde kracht of controle van de bekkenbodemspieren, leidend tot klachten zoals urineverlies.",
    "Lichamelijke vermoeidheid": "Uitputting van het lichaam, vaak door fysieke inspanning, ziekte of slaaptekort.",
    "Kinderen in de groei": "Ondersteuning van de lichamelijke en mentale ontwikkeling van opgroeiende kinderen.",
    "Gevoeligheid voor veroudering": "Versneld optreden van leeftijdsgebonden veranderingen in lichaam en geest.",
    "Andropauze": "Hormonale veranderingen bij mannen op middelbare leeftijd, vergelijkbaar met de vrouwelijke menopauze.",
    "Onregelmatige menstruatie": "Variaties in duur, intensiteit of frequentie van de menstruatiecyclus.",
    "Virusinfecties": "Ziekten veroorzaakt door virussen, zoals griep, verkoudheid of herpes.",
    "Zweetvoeten": "Overmatige transpiratie van de voeten, vaak gepaard met geurvorming.",
    "Neerslachtigheid": "Aanhoudend gevoel van somberheid of verlies van levensvreugde.",
    "Depressie": "Psychische aandoening gekenmerkt door langdurige neerslachtigheid, verlies van interesse en energie.",
    "Geestelijke disbalans": "Verstoorde mentale toestand, vaak gepaard met wisselende stemmingen en verminderde veerkracht.",
    "Angst (aanvallen)": "Plotselinge, intense episodes van angst en paniek, vaak zonder directe aanleiding.",
    "Stemmingsstoornis": "Psychische aandoening waarbij stemming langdurig abnormaal verhoogd of verlaagd is.",
    "Vitaliteit (gebrek aan)": "Tekort aan energie, levenslust en motivatie om dagelijkse activiteiten uit te voeren.",
    "Lage energieniveaus": "Verminderde fysieke of mentale kracht, resulterend in snel optreden van vermoeidheid.",
    "Diabetes type 2": "Chronische stofwisselingsziekte gekenmerkt door insulineresistentie en hoge bloedsuikerwaarden.",
    "Sombere stemming": "Aanhoudend gevoel van melancholie of verdriet zonder duidelijke oorzaak.",
    "Tabaksverslaving": "Afhankelijkheid van nicotinegebruik, vaak leidend tot gezondheidsproblemen.",
    "Menstruatieklachten": "Pijn, krampen of andere ongemakken die optreden rondom de menstruatie.",
    "Premenstrueel syndroom (pms)": "Verzameling van fysieke en emotionele symptomen in de dagen voorafgaand aan de menstruatie.",
    "Gespannen borsten": "Pijnlijke of gezwollen borsten, vaak gerelateerd aan hormonale schommelingen.",
    "Maag-darmkramp": "Pijnlijke samentrekkingen van de spieren in maag of darmen, vaak gepaard met spijsverteringsklachten.",
    "Onvoldoende borstvoeding": "Onvoldoende melkproductie bij vrouwen die borstvoeding geven.",
    "Hooikoorts": "Allergische reactie op pollen, met symptomen zoals niezen, jeukende ogen en loopneus.",
    "Jeuk": "Onaangename sensatie van de huid die leidt tot de behoefte om te krabben.",
    "Huisstofmijtallergie": "Allergische reactie op uitwerpselen van huisstofmijten, vaak met symptomen zoals niezen en jeukende ogen.",
    "Allergie": "Overmatige reactie van het immuunsysteem op doorgaans onschadelijke stoffen zoals pollen, voedsel of dieren.",
    "Huidproblemen": "Verzameling van aandoeningen zoals eczeem, acne, psoriasis of schimmelinfecties die de huid aantasten.",
    "Astma": "Chronische ontstekingsziekte van de luchtwegen, gekenmerkt door benauwdheid, hoesten en piepende ademhaling.",
    "Bronchitis": "Ontsteking van de luchtwegen in de longen, vaak gepaard met hoesten en slijmvorming.",
    "Baarmoederverzakking": "Verzakking van de baarmoeder in de vagina als gevolg van verzwakte bekkenbodemspieren.",
    "Menstruatiepijn": "Pijnlijke samentrekkingen van de baarmoeder tijdens de menstruatie.",
    "Pms": "Premenstrueel syndroom: fysieke en emotionele klachten die enkele dagen voor de menstruatie optreden.",
    "Overmatige menstruatie": "Zeer zware of langdurige menstruatiebloedingen, medisch ook wel menorragie genoemd.",
    "Zwakte (gebrek aan)": "Algemeen gevoel van lichamelijke krachteloosheid of verminderde energie.",
    "Spierzwakte": "Verminderde kracht in één of meerdere spiergroepen, leidend tot bewegingsbeperkingen.",
    "Covid-19": "Virale infectie veroorzaakt door het coronavirus SARS-CoV-2, met symptomen variërend van mild tot ernstig.",
    "Ziekte van pfeiffer": "Infectieuze mononucleosis, veroorzaakt door het Epstein-Barr-virus, gekenmerkt door extreme vermoeidheid en koorts.",
    "Ziekte van parkinson": "Progressieve neurologische aandoening die beweging, spiercontrole en evenwicht aantast.",
    "Ziekte van sjögren": "Auto-immuunziekte die leidt tot droogte van ogen, mond en andere slijmvliezen.",
    "Ziekte van hirschsprung": "Aangeboren aandoening waarbij zenuwcellen in delen van de dikke darm ontbreken, leidend tot ernstige obstipatie.",
    "Prikkelbare darm syndroom": "Chronische darmaandoening gekenmerkt door buikpijn, een opgeblazen gevoel en veranderingen in de stoelgang.",
    "Kaalheid (mannen)": "Erfelijke haaruitval bij mannen, beginnend met terugtrekkende haarlijn en dunner wordend haar op de kruin.",
    "Nycturie (nachtelijk plassen)": "Frequent wakker worden 's nachts om te plassen, vaak als gevolg van medische aandoeningen.",
    "Incontinentie": "Onvrijwillig verlies van urine of ontlasting, variërend van druppels tot volledige controleverlies.",
    "Moeilijk plassen": "Moeizame urinelozing, vaak veroorzaakt door blokkades of infecties van de urinewegen.",
    "Zin in sex": "Behoefte of verlangen naar seksuele activiteit, beïnvloed door fysieke, hormonale en emotionele factoren.",
}








