planten_info = [
    {
        "naam": "Acidophilus",
        "botanische_naam": "Lactobacillus acidophilus",
        "beschrijving": "In onze darmen werken miljarden bacteriën actief samen aan een goede spijsvertering en het op peil houden van ons immuunsysteem. Acidophilus bevat een mengsel van drie synergetisch werkende bacteriestammen die de balans van de darmflora herstellen. Het helpt bij diarree, voedselvergiftiging, antibiotica, stress of een schimmelinfectie. Versterkt de natuurlijke weerstand tegen bacteriën en schimmels. Elke bacteriestam bevat 2,5 miljard levensvatbare micro-organismen.",
        "te_gebruiken_bij": "verstoorde darmflora, schimmelinfecties, darmparasieten, herstel balans darmflora na antibioticakuur, herstel balans darmflora bij diëten en vasten",
        "gebruikt_plantendeel": "Lactobacillus acidophilus, Lactobacillus bulgaricus, Bifidobacterium bifidum",
        "aanbevolen_combinaties": "Acidophilus + Cat’s Claw, Acidophilus + Grote Klis, Acidophilus + Vitamine D3 plantaardig",
        "niet_te_gebruiken_bij": "",
        "categorie_kleur": "",
        "details": "Probiotica. Mengsel van 3 bacteriestammen. Bevat stabiele bacteriestammen die de maag passeren en actief zijn in de darmen.",
        "afbeelding": "acidophilus.jpg",
    },
    {
        "naam": "Aloë Vera",
        "botanische_naam": "Aloë barbadensis",
        "beschrijving": "Aloë Vera is een vetplant uit Mexico met dikke puntige bladeren. Aloë barbadensis is de krachtigste soort, al eeuwenlang gebruikt door verschillende culturen. Het sap ontgift het lichaam, bevordert de spijsvertering, herstelt slijmvlieslagen en verhoogt de opname van voedingsstoffen. Het verlaagt de bloedsuikerspiegel en bevat 20-22 aminozuren, waarvan 7-8 essentieel zijn. Vooral geschikt voor sporters en mensen met spijsverteringsproblemen.",
        "te_gebruiken_bij": "slechte spijsvertering, buikpijn, opgeblazen gevoel, maagzuur, bacteriële infecties, schimmelinfecties, diabetes, vermoeidheid, aanvullen aminozuren bij sporters, detox voor maag en darmen",
        "gebruikt_plantendeel": "Bladsap (HAD vrij)",
        "aanbevolen_combinaties": "Aloë Vera + Lithothamnium (brandend maagzuur), Aloë Vera + Artisjok (spijsvertering)",
        "niet_te_gebruiken_bij": "zwangerschap, borstvoedingsperiode",
        "categorie_kleur": "",
        "details": "Bevat 20-22 aminozuren (waarvan 7-8 essentieel). Werkt ontgiftend, bloedsuikerverlagend, slijmvliesherstellend en is rijk aan werkzame stoffen.",
        "afbeelding": "aloe_vera.jpg",
    },
    {
        "naam": "Artisjok",
        "botanische_naam": "Cynara scolymus",
        "beschrijving": "Artisjok is vermoedelijk een gecultiveerde vorm van kardoen, afkomstig uit Afrika en geteeld in Frankrijk. In de fytotherapie worden vooral de bladeren gebruikt. Het bevat cynarine, dat de galproductie en -afbraak stimuleert. Artisjok ondersteunt lever- en galblaasproblemen, stimuleert de spijsvertering, verlaagt cholesterol en werkt bloedzuiverend. Het wordt ingezet bij detoxkuren, vooral na overmatig alcoholgebruik.",
        "te_gebruiken_bij": "slechte spijsvertering, leverproblemen, alcoholmisbruik, kater, galblaasproblemen, anorexia, gezwollen buik, overproductie en afbouwen borstvoeding, preventie borstontsteking",
        "gebruikt_plantendeel": "Blad",
        "aanbevolen_combinaties": "Artisjok + Mariadistel (leverproblemen), Artisjok + Melisse (moeilijke spijsvertering), Artisjok + Paardenbloem (anorexia), Artisjok + Grote Klis + Paardenbloem (gezwollen buik)",
        "niet_te_gebruiken_bij": "zwangerschap, borstvoedingsperiode",
        "categorie_kleur": "",
        "details": "Bevat cynarine. Stimuleert lever en galblaas, ondersteunt bij detox na alcoholgebruik. Werkt bloedzuiverend en cholesterolverlagend. Kan melkafscheiding remmen.",
        "afbeelding": "artisjok.jpg",
    },
    {
        "naam": "Ashwagandha",
        "botanische_naam": "Withania somnifera",
        "beschrijving": "Ashwagandha is een groenblijvende struik uit Azië en Afrika met medicinaal gebruikte wortels. In de ayurvedische geneeskunde wordt het ingezet als verjongend middel tegen veroudering, vermoeidheid en slaaptekort. Het versterkt het zenuwstelsel, werkt libidoverhogend en bevordert de vruchtbaarheid. Bekend als de 'ginseng' van de Ayurveda.",
        "te_gebruiken_bij": "geringe spermaproductie, vruchtbaarheidsproblemen, impotentie, veroudering, overspannenheid, burn-out, stress",
        "gebruikt_plantendeel": "Wortel",
        "aanbevolen_combinaties": "Ashwagandha + Boswellia (fibromyalgie), Ashwagandha + Royal Jelly (herstel na ziekte), Ashwagandha + Gember (libido), Ashwagandha + Bacopa (Alzheimer)",
        "niet_te_gebruiken_bij": "zwangerschap, borstvoedingsperiode",
        "categorie_kleur": "",
        "details": "Versterkt het zenuw- en hormonaal stelsel. Remt veroudering en vrije radicalen. Bevordert libido, vruchtbaarheid en herstel. Ook effectief bij stress en burn-out.",
        "afbeelding": "ashwagandha.jpg",
    },
    {
        "naam": "Avena sativa",
        "botanische_naam": "Avena sativa",
        "beschrijving": "Avena sativa, oftewel haver, is een eetbare plant uit de grassenfamilie die ook medicinaal wordt ingezet. Het werkt ondersteunend bij overprikkeling van het zenuwstelsel door stressvolle situaties zoals examens of relationele problemen. Het bevordert de nachtrust, helpt bij afkickverschijnselen van alcohol, drugs of nicotine, en ondersteunt traumaverwerking.",
        "te_gebruiken_bij": "slapeloosheid, traumaverwerking, nervositeit, innerlijke onrust, afkickverschijnselen, stress, prikkelbaarheid",
        "gebruikt_plantendeel": "Zaad",
        "aanbevolen_combinaties": "Avena sativa + Melisse (paniekaanvallen, nachtmerries), Avena sativa + Russische Ginseng (burn-out, oververmoeidheid)",
        "niet_te_gebruiken_bij": "",
        "categorie_kleur": "",
        "details": "Werkt kalmerend op het zenuwstelsel. Bevordert nachtrust, vermindert stress en prikkelbaarheid. Helpt bij afkicken van verslavingen en traumaverwerking.",
        "afbeelding": "avena_sativa.jpg",
    },
    {
        "naam": "Bacopa",
        "botanische_naam": "Bacopa monniera",
        "beschrijving": "Bacopa, ook wel bekend als Brahmi in de Ayurvedische geneeskunde, groeit in moerasgebieden en bevat werkzame bacosiden. Het ondersteunt het geheugen, bevordert de concentratie, en beschermt het hersenweefsel. Het is effectief bij kinderen met ADHD en ouderen met geheugenproblemen. Bacopa verhoogt ook de GABA-concentraties in de hersenen, wat gunstig is bij epilepsie.",
        "te_gebruiken_bij": "geheugen­zwakte, ADHD, leerproblemen, concentratiestoornissen, dementie, epilepsie",
        "gebruikt_plantendeel": "Blad en bovengronds bloeiend gedeelte",
        "aanbevolen_combinaties": "Bacopa + Ginkgo (concentratieproblemen), Bacopa + Ashwagandha (Alzheimer), Bacopa + Lijnzaadolie (ADHD)",
        "niet_te_gebruiken_bij": "zwangerschap, borstvoedingsperiode",
        "categorie_kleur": "",
        "details": "Bevat bacosiden. Ondersteunt geheugen, concentratie en hersenfunctie. Vermijd combinatie met melkproducten. Werkt bij ADHD, dementie en epilepsie.",
        "afbeelding": "bacopa.jpg",
    },
    {
        "naam": "Biergist",
        "botanische_naam": "Saccharomyces cerevisiae",
        "beschrijving": "Biergist is een microscopische zwam die voorkomt op fruit en in biermost. Het is rijk aan essentiële aminozuren, B-vitaminen en mineralen. Reactieve biergist bevat het hoogste gehalte levende gist (1 miljard per gram) en ondersteunt huid, haar, nagels en darmflora. Het is populair bij vegetariërs vanwege het B12-gehalte.",
        "te_gebruiken_bij": "broze haren, zwakke nagels, jeugdpuistjes, acne, steenpuisten, droge huid, ruwe huid, haaruitval na bevalling, verstoorde darmflora",
        "gebruikt_plantendeel": "Reactiverbare gist",
        "aanbevolen_combinaties": "Biergist + Borage-olie (stralende huid), Biergist + Brandnetel (broze nagels), Biergist + Zaagbladpalm (haaruitval mannen), Biergist + Grote Klis (acne, eczeem)",
        "niet_te_gebruiken_bij": "schimmelinfecties (Candida albicans), gistvrij dieet",
        "categorie_kleur": "",
        "details": "Rijk aan B-complex, aminozuren en mineralen. Anti-bacterieel, huidherstellend en darmflora-ondersteunend. Niet geschikt bij Candida of gistvrij dieet.",
        "afbeelding": "biergist.jpg",
    },
    {
        "naam": "Blauwe Bosbesvrucht",
        "botanische_naam": "Vaccinium myrtillus",
        "beschrijving": "De Blauwe Bosbes is een halfstruik die groeit op vochtige, humusrijke gronden in Europa. De vrucht bevat vitamine A, C, tanninen en anthocyanosiden. Deze stoffen werken antiseptisch bij diarree en verbeteren het gezichtsvermogen, vooral in het donker. Ook worden vermoeide ogen sneller hersteld en blijkt het een gunstig effect te hebben op de regulatie van bloedsuikers bij diabetes.",
        "te_gebruiken_bij": "diarree, buikpijn, vermoeide ogen, tranende ogen, nachtblindheid, diabetes",
        "gebruikt_plantendeel": "Vrucht",
        "aanbevolen_combinaties": "Blauwe Bosbesvrucht + Plantaardige Kool (diarree), Blauwe Bosbesvrucht + Lijnzaadolie (droge ogen, slecht zicht)",
        "niet_te_gebruiken_bij": "",
        "categorie_kleur": "",
        "details": "Rijk aan anthocyanosiden, vitamine A en C. Werkt antiseptisch, verbetert nachtzicht en ondersteunt bloedsuikerregulatie. Herstelt vermoeide ogen bij veel beeldschermgebruik.",
        "afbeelding": "blauwe_bosbesvrucht.jpg",
    },
    {
        "naam": "Borage-olie",
        "botanische_naam": "Borago officinalis",
        "beschrijving": "Borage-olie, afkomstig van de zaden van het Komkommerkruid, is rijk aan gammalinoleenzuur en linolzuur. Het helpt bij huidveroudering, maakt de huid soepel en versterkt haar en nagels. Het ondersteunt een evenwichtige hormoonhuishouding bij vrouwen en is effectief bij eczeem, psoriasis en huidaandoeningen zoals luier­eczeem en dauwworm.",
        "te_gebruiken_bij": "huidveroudering, rimpels, zwangerschapsstriemen, eczeem, psoriasis, premenstrueel syndroom, luier­eczeem, dauwworm",
        "gebruikt_plantendeel": "Zaad",
        "aanbevolen_combinaties": "Borage-olie + Grote Klis (stralende huid), Borage-olie + Venkel (menstruatiekrampen)",
        "niet_te_gebruiken_bij": "",
        "categorie_kleur": "",
        "details": "Rijk aan GLA en linolzuur. Werkt huidherstellend, hormoonbalansondersteunend en ontstekingsremmend. Geschikt voor lokaal gebruik bij huidproblemen.",
        "afbeelding": "borage_olie.jpg",
    },
    {
        "naam": "Boswellia",
        "botanische_naam": "Boswellia serrata",
        "beschrijving": "Boswellia is een boom uit India waarvan het hars wordt geoogst en gezuiverd voor gebruik in moderne kruidengeneeskunde. De werkzame boswelliazuren binden zich aan ontstekingsveroorzakende stoffen en hebben een ontstekingsremmende én pijnstillende werking. Boswellia is effectief bij reumatische klachten, darmziekten zoals colitis ulcerosa en de ziekte van Crohn, en hielspoor.",
        "te_gebruiken_bij": "gewrichtsslijtage, reuma, artrose, jicht, colitis ulcerosa, ziekte van Crohn, slijmbeursontsteking, carpaal tunnel syndroom, hielspoor, fibromyalgie",
        "gebruikt_plantendeel": "Hars",
        "aanbevolen_combinaties": "Boswellia + Heermoes (slijmbeursontsteking, carpaal tunnel syndroom, hielspoor), Boswellia + Ashwagandha (fibromyalgie)",
        "niet_te_gebruiken_bij": "zwangerschap, borstvoedingsperiode",
        "categorie_kleur": "",
        "details": "Bevat boswelliazuren. Werkt ontstekingsremmend en licht pijnstillend. Geschikt bij reumatische aandoeningen, darmontstekingen en hielspoor. Combineert goed met Heermoes.",
        "afbeelding": "boswellia.jpg",
    },
    {
        "naam": "Brandnetel",
        "botanische_naam": "Urtica dioica",
        "beschrijving": "Brandnetel is een veelvoorkomende plant met prikkelende haren die irritatie veroorzaken bij aanraking. De plant is rijk aan mineralen zoals calcium, zink en silicium, en bevat ook vitamine B2, B5 en foliumzuur. Brandnetel bevordert de haargroei, versterkt nagels, ondersteunt bij acne en werkt remineraliserend. Het helpt bij gewrichtsslijtage, bloedarmoede en is effectief bij verstuikingen en kneuzingen.",
        "te_gebruiken_bij": "haaruitval, zwakke nagels, afgesleten kraakbeen, acne, mee-eters, bloedarmoede, verstuiking, kneuzingen",
        "gebruikt_plantendeel": "Bovengronds gedeelte",
        "aanbevolen_combinaties": "Brandnetel + Biergist (broze nagels, haaruitval), Brandnetel + Duivelsklauw (verstuiking)",
        "niet_te_gebruiken_bij": "zwangerschap, borstvoedingsperiode",
        "categorie_kleur": "",
        "details": "Rijk aan ijzer, calcium, silicium en zink. Werkt remineraliserend, versterkt haar en nagels, ondersteunt bij bloedarmoede en kraakbeenafbraak. Ook geschikt bij huidproblemen.",
        "afbeelding": "brandnetel.jpg",
    },
    {
        "naam": "Canadese Geelwortel",
        "botanische_naam": "Hydrastis canadensis",
        "beschrijving": "Canadese Geelwortel is een bosplant uit Noord-Amerika, oorspronkelijk gebruikt door inheemse volkeren. De wortel is rijk aan berberine, een krachtige antibacteriële stof. Het versterkt de slijmvliezen van de bovenste luchtwegen, werkt ontstekingsremmend en verhoogt de weerstand bij infecties zoals griep, herpes en keelontsteking. Ook effectief bij vaginitis.",
        "te_gebruiken_bij": "voorhoofdsholte ontsteking, sinusitis, keelontsteking, amandelontsteking, luchtweginfecties, vaginitis, herpes simplex, griep, verkoudheid",
        "gebruikt_plantendeel": "Wortel",
        "aanbevolen_combinaties": "Canadese Geelwortel + Cat’s Claw (vaginale schimmelinfectie), Canadese Geelwortel + Vrouwenmantel (vaginale ontsteking)",
        "niet_te_gebruiken_bij": "zwangerschap, borstvoedingsperiode",
        "categorie_kleur": "",
        "details": "Bevat berberine. Werkt antibacterieel en ontstekingsremmend. Geschikt bij luchtweginfecties, keel- en vaginale ontstekingen. Verhoogt de weerstand.",
        "afbeelding": "canadese_geelwortel.jpg",
    },
    {
        "naam": "Cat’s Claw",
        "botanische_naam": "Uncaria tomentosa",
        "beschrijving": "Cat’s Claw is een klimplant uit de Peruaanse jungle die zich met klauwachtige uitsteeksels vasthecht aan bomen. De schors bevat alkaloïden en glycosiden die het immuunsysteem versterken, ontstekingen remmen en het lichaam van binnenuit reinigen na antibioticakuren. Cat’s Claw is werkzaam bij inwendige infecties, darmproblemen, de ziekte van Crohn en de ziekte van Lyme.",
        "te_gebruiken_bij": "koortsblaasjes, aften, verminderde weerstand, ontstekingen, gewrichtsontstekingen, ontgifting na antibioticakuur, ziekte van Crohn, ziekte van Lyme",
        "gebruikt_plantendeel": "Schors",
        "aanbevolen_combinaties": "Cat’s Claw + Lijnzaadolie (ziekte van Lyme), Cat’s Claw + Weegbree (gordelroos), Cat’s Claw + Canadese Geelwortel (vaginale schimmelinfectie), Cat’s Claw + Vitamine D3 plantaardig (ziekte van Pfeiffer)",
        "niet_te_gebruiken_bij": "zwangerschap, borstvoedingsperiode",
        "categorie_kleur": "",
        "details": "Bevat alkaloïden en glycosiden. Versterkt het immuunsysteem, werkt antibacterieel, antiviraal en ontstekingsremmend. Ondersteunt bij Lyme, Crohn, infecties en detox na antibiotica.",
        "afbeelding": "cats_claw.jpg",
    },
    {
        "naam": "Cranberry",
        "botanische_naam": "Vaccinium macrocarpon",
        "beschrijving": "De Cranberry of Veenbes is een dieprode vrucht die oorspronkelijk uit Noord-Amerika komt en nu ook op de Waddeneilanden groeit. De bes is rijk aan organische zuren die voorkomen dat de E-coli bacterie zich aan de blaaswand hecht, waardoor blaasontstekingen worden bestreden. Het vermindert ook de geur van urine en wordt vaak gecombineerd met vitamine C of probiotica voor extra ondersteuning.",
        "te_gebruiken_bij": "blaasontsteking, urineweginfectie, vaak urineren, weinig urineren, branderig gevoel bij het plassen, sterk geurende urine",
        "gebruikt_plantendeel": "Bes",
        "aanbevolen_combinaties": "Cranberry + Acidophilus (blaasontsteking), Cranberry + Pompoenpitolie (infectie in resturine bij mannen)",
        "niet_te_gebruiken_bij": "nierstenen",
        "categorie_kleur": "",
        "details": "Rijk aan organische zuren. Voorkomt hechting van E-coli aan blaaswand. Werkt urinezuurverlagend. Combineert goed met vitamine C en probiotica bij blaasverzorging.",
        "afbeelding": "cranberry.jpg",
    },
    {
        "naam": "Curcuma + Piperine",
        "botanische_naam": "Curcuma longa",
        "beschrijving": "Curcuma, ook bekend als geelwortel, wordt gewonnen uit de wortelstok en is bekend om zijn medische toepassingen en als natuurlijke kleurstof in de Aziatische keuken. Curcumine, de actieve stof, ondersteunt het cardiovasculaire systeem, verlaagt cholesterol en bevordert de leverfunctie. Het heeft bovendien een schimmelremmende werking tegen Candida. In combinatie met piperine uit zwarte peper wordt de opname van curcumine sterk verbeterd.",
        "te_gebruiken_bij": "colitis ulcerosa, ziekte van Crohn, galstenen (preventie), leverbeschadiging, alcoholgebruik, medicijngebruik, te hoog cholesterol, candida, witte vloed, gewrichtspijn",
        "gebruikt_plantendeel": "Wortel",
        "aanbevolen_combinaties": "Curcuma + Boswellia (ziekte van Crohn), Curcuma + Duivelsklauw (gewrichtspijnen), Curcuma + Heermoes (peesontsteking)",
        "niet_te_gebruiken_bij": "geblokkeerde galwegen, zwangerschap, borstvoedingsperiode",
        "categorie_kleur": "",
        "details": "Bevat curcumine en wordt versterkt met piperine voor betere opname. Werkt ontstekingsremmend, cholesterolverlagend en leverbeschermend. Effectief tegen Candida.",
        "afbeelding": "curcuma_piperine.jpg",
    },
    {
        "naam": "Damiana",
        "botanische_naam": "Turnera aphrodisiaca",
        "beschrijving": "Damiana is een aromatische plant uit Mexico en Zuid-Amerika, ook wel bekend als liefdeskruid. Het staat bekend om zijn libidoversterkende werking voor zowel mannen als vrouwen. Damiana stimuleert de geslachtsorganen en verbetert de gemoedstoestand. Het heeft een licht psychoactieve werking en wordt traditioneel ingezet bij stress, zenuwzwakte en seksuele disfuncties.",
        "te_gebruiken_bij": "seksueel onvermogen, libido opwekkend, depressiviteit, zenuwzwakte, frigiditeit",
        "gebruikt_plantendeel": "Blad en stengel",
        "aanbevolen_combinaties": "Damiana + Sint Janskruid (depressiviteit), Damiana + Maca (libido cocktail)",
        "niet_te_gebruiken_bij": "zwangerschap, borstvoedingsperiode",
        "categorie_kleur": "",
        "details": "Afrodisiacum met stimulerende werking op geslachtsorganen en zenuwstelsel. Werkt libidoverhogend en stemmingsverbeterend. Kan uitwendig en inwendig gebruikt worden.",
        "afbeelding": "damiana.jpg",
    },
    {
        "naam": "Driekleurig Viooltje",
        "botanische_naam": "Viola tricolor",
        "beschrijving": "Het Driekleurig Viooltje is een inheemse plant uit Europa met geel, wit en violetgekleurde bloemen. De plant is rijk aan flavonoïden, saponosiden, anthocyanosiden en vitamine E. Het ondersteunt de uitscheidingsfuncties van lever en nieren en heeft een bloedzuiverende en ontstekingsremmende werking. Wordt ingezet bij diverse chronische huidaandoeningen en allergieën.",
        "te_gebruiken_bij": "eczeem, psoriasis, luier­eczeem, dauwworm, impetigo, acne",
        "gebruikt_plantendeel": "Bovengronds bloeiend gedeelte",
        "aanbevolen_combinaties": "Driekleurig Viooltje + Grote Klis (acne)",
        "niet_te_gebruiken_bij": "",
        "categorie_kleur": "",
        "details": "Werkt bloedzuiverend, ontstekingsremmend en huidherstellend. Bevat vitamine E tegen celveroudering. Geschikt bij huidaandoeningen zoals eczeem, acne en impetigo.",
        "afbeelding": "driekleurig_viooltje.jpg",
    },
    {
        "naam": "Duivelsklauw",
        "botanische_naam": "Harpagophytum procumbens",
        "beschrijving": "Duivelsklauw is een plant uit de Kalahari-woestijn in Zuid-Afrika. De bijwortels bevatten ontstekingsremmende en pijnstillende stoffen die gewrichten soepel houden. Het wordt ingezet bij gewrichtspijn, peesontstekingen en jicht. Uitwendig als gel en inwendig in combinatie met andere planten werkt het effectief tegen reuma, artritis en overbelastingsklachten bij sporters.",
        "te_gebruiken_bij": "reuma, gewrichtspijn, artrose, artritis, ischias, jicht, peesontstekingen, tennisarm, verstuiking",
        "gebruikt_plantendeel": "Bijwortel",
        "aanbevolen_combinaties": "Duivelsklauw + Brandnetel (verstuiking), Duivelsklauw + Curcuma (gewrichtspijnen), Duivelsklauw + Lithothamnium + Duivelsklauw gel (reuma, artritis, jicht)",
        "niet_te_gebruiken_bij": "zwangerschap, borstvoedingsperiode",
        "categorie_kleur": "",
        "details": "Werkt pijnstillend en ontstekingsremmend. Ondersteunt gewrichtsfunctie, verlicht sportblessures en reumatische klachten. Inwendig en uitwendig toepasbaar.",
        "afbeelding": "duivelsklauw.jpg",
    },
    {
        "naam": "Echinacea",
        "botanische_naam": "Echinacea purpurea",
        "beschrijving": "Echinacea, of rode zonnehoed, is een plant uit Noord-Amerika die traditioneel door de indianen werd gebruikt. De wortel bevat bestanddelen zoals echinacoside, rutoside en polysacchariden die een bewezen ontstekingsremmende en weerstandverhogende werking hebben. Echinacea wordt preventief ingezet tijdens de wintermaanden en ondersteunt het immuunsysteem bij griep, verkoudheid en andere infecties.",
        "te_gebruiken_bij": "griep, verkoudheid, infecties, ontstekingen, verminderde weerstand, preventie van winterziekten",
        "gebruikt_plantendeel": "Wortel",
        "aanbevolen_combinaties": "Echinacea + Propolis (immuunstimulatie, herpesvirus, keelontsteking)",
        "niet_te_gebruiken_bij": "",
        "categorie_kleur": "",
        "details": "Bevat echinacoside en polysacchariden. Klinisch bewezen effect bij versterking van het immuunsysteem. Werkt preventief en curatief bij infecties en winterkwalen.",
        "afbeelding": "echinacea.jpg",
    },
    {
        "naam": "Fenegriek",
        "botanische_naam": "Trigonella foenum-graecum",
        "beschrijving": "Fenegriek is een eenjarige plant afkomstig uit het Middellandse Zeegebied. De zaadjes bevatten veel proteïnen, lipiden en saponinen, en worden gebruikt bij gebrek aan eetlust, voor gewichtstoename en bij bodybuilding. Fenegriek stimuleert de borstvoeding, bevordert borstgroei door oestrogeenachtige werking en ondersteunt sporters bij spierontwikkeling.",
        "te_gebruiken_bij": "gebrek aan eetlust, anorexia, gewichtstoename, bodybuilding, sporters, borstgroei, borstvoeding stimuleren",
        "gebruikt_plantendeel": "Zaad",
        "aanbevolen_combinaties": "Fenegriek + Hop (borstvergroting), Fenegriek + Russische Ginseng (spierkrachtontwikkeling)",
        "niet_te_gebruiken_bij": "zwangerschap",
        "categorie_kleur": "",
        "details": "Rijk aan saponinen, proteïnen en lipiden. Werkt eetlustopwekkend, bevordert borstvoeding en borstontwikkeling. Populair bij sporters voor natuurlijke spieropbouw.",
        "afbeelding": "fenegriek.jpg",
    },
    {
        "naam": "Garcinia",
        "botanische_naam": "Garcinia cambogia",
        "beschrijving": "Garcinia is een pompoenachtige vrucht uit Zuidoost-Azië met een schil die rijk is aan HCA (hydroxycitroenzuur). HCA remt de omzetting van suikers in vet en vermindert de trek in zoetigheid. Garcinia is daarom uitermate geschikt voor mensen met snoepzucht of overgewicht en wordt veel gebruikt in afslankkuren.",
        "te_gebruiken_bij": "afslankkuren, overgewicht, zwaarlijvigheid, trek in zoetigheid, snoep, cellulitis",
        "gebruikt_plantendeel": "Schil",
        "aanbevolen_combinaties": "Garcinia + Konjac (grote eetlust), Garcinia + Javaanse Thee (overgewicht)",
        "niet_te_gebruiken_bij": "zwangerschap, borstvoedingsperiode",
        "categorie_kleur": "",
        "details": "Bevat HCA (hydroxycitroenzuur) dat suikermetabolisme beïnvloedt. Onderdrukt eetlust, voorkomt vetopslag en vermindert snoepzucht. Onderdeel van vele moderne afslankprogramma's.",
        "afbeelding": "garcinia.jpg",
    },
    {
        "naam": "Gember",
        "botanische_naam": "Zingiber officinale",
        "beschrijving": "Gember is een aromatische wortelstok afkomstig uit Zuidoost-Azië, en een belangrijk element in de Chinese geneeskunst. De wortel bevat ginerolen en shogaol, stoffen die werkzaam zijn bij reisziekte, misselijkheid, zwangerschapsbraken en migraine. Gember ondersteunt tevens de spijsvertering en kan preventief ingezet worden bij maag- en darmzweren.",
        "te_gebruiken_bij": "misselijkheid, overgeven, reisziekte, zwangerschapsbraken, hoofdpijn, migraine",
        "gebruikt_plantendeel": "Wortelstok",
        "aanbevolen_combinaties": "Gember + Venkel (misselijkheid), Gember + Ashwagandha (libido opwekkend)",
        "niet_te_gebruiken_bij": "",
        "categorie_kleur": "",
        "details": "Bevat ginerolen en shogaol. Werkt maagversterkend, anti-emetisch en pijnstillend bij migraine. Effectief bij bewegingsziekte en ondersteuning van de spijsvertering.",
        "afbeelding": "gember.jpg",
    },
    {
        "naam": "Ginkgo",
        "botanische_naam": "Ginkgo biloba",
        "beschrijving": "Ginkgo biloba is een oeroude boomsoort uit China die bekendstaat om zijn medicinale bladeren. De bladeren bevatten flavonoïden die de doorbloeding verbeteren, met name in de haarvaten rond de hersenen. Ginkgo wordt ingezet bij geheugen- en concentratieproblemen, oorsuizen en circulatieproblemen zoals koude handen en voeten.",
        "te_gebruiken_bij": "geheugenproblemen, concentratieverlies, koude handen en voeten, ouderdomsvergeetachtigheid, oorsuizen (tinnitus)",
        "gebruikt_plantendeel": "Blad",
        "aanbevolen_combinaties": "Ginkgo + Bacopa (concentratieproblemen), Ginkgo + Sint Janskruid (oorsuizen), Ginkgo + Rozemarijn (geheugen)",
        "niet_te_gebruiken_bij": "zwangerschap, borstvoedingsperiode",
        "categorie_kleur": "",
        "details": "Bevat flavonoïden die de microcirculatie verbeteren. Verhoogt zuurstoftoevoer naar de hersenen en helpt bij geheugenverlies, oorsuizen en perifere circulatieklachten.",
        "afbeelding": "ginkgo.jpg",
    },
    {
        "naam": "Ginseng",
        "botanische_naam": "Panax ginseng",
        "beschrijving": "Ginseng is een krachtig tonicum dat traditioneel in China en Korea als koninklijk kruid werd beschouwd. De wortel bevordert zowel de fysieke als mentale prestaties, verlaagt het bloedsuiker- en melkzuurgehalte en verhoogt de zuurstoftoevoer naar de spieren. Ginseng is rijk aan vitaminen, mineralen en aminozuren en wordt ingezet bij vermoeidheid, spierpijn en overspanning.",
        "te_gebruiken_bij": "overspannenheid, vermoeidheid, energietekort, spierpijn, verbetering van geestelijke prestaties",
        "gebruikt_plantendeel": "Wortel",
        "aanbevolen_combinaties": "Ginseng + Royal Jelly (lichamelijke vermoeidheid), Ginseng + Guarana (onmiddellijke oppepper), Ginseng + Gember (seksuele energie)",
        "niet_te_gebruiken_bij": "zwangerschap, borstvoedingsperiode",
        "categorie_kleur": "",
        "details": "Adaptogeen met versterkende werking. Verhoogt lichamelijke en mentale prestaties. Rijk aan B-vitaminen, mineralen en aminozuren. Pas na 6 jaar geoogst voor optimale werking.",
        "afbeelding": "ginseng.jpg",
    },
    {
        "naam": "Goudpapaver",
        "botanische_naam": "Eschscholtzia californica",
        "beschrijving": "Goudpapaver, ook wel slaappapaver genoemd, is een rustgevende plant afkomstig uit Californië. De plant bevat alkaloïden die de slaapkwaliteit verbeteren zonder verslavende of verdovende bijwerkingen. Goudpapaver is inzetbaar bij slapeloosheid, inslaapproblemen, nachtmerries en nervositeit. Ook effectief bij bedplassen bij kinderen.",
        "te_gebruiken_bij": "inslaapproblemen, bedplassen, overactiviteit, angst, nervositeit, slapeloosheid, nachtmerries",
        "gebruikt_plantendeel": "Bovengronds bloeiend gedeelte",
        "aanbevolen_combinaties": "Goudpapaver + Valeriaan (inslaapproblemen), Goudpapaver + Meidoorn (hartkloppingen door angst), Goudpapaver + Passiebloem (ongestoorde nachtrust), Goudpapaver + Russische Ginseng (bekkenbodeminstabiliteit)",
        "niet_te_gebruiken_bij": "zwangerschap, borstvoedingsperiode",
        "categorie_kleur": "",
        "details": "Natuurlijk rustgevend middel zonder bijwerkingen. Geschikt voor jong en oud. Ondersteunt bij slaapstoornissen, angst en bedplassen. Veroorzaakt geen gewenning.",
        "afbeelding": "goudpapaver.jpg",
    },
    {
        "naam": "Griffonia (5-HTP)",
        "botanische_naam": "Griffonia simplicifolia",
        "beschrijving": "Griffonia simplicifolia is een klimplant uit West-Afrika, bekend om zijn zaden die rijk zijn aan 5-HTP. In het lichaam wordt 5-HTP omgezet in serotonine, wat helpt bij stemmingsverbetering, slaapregulatie en pijnbestrijding. Griffonia wordt effectief ingezet bij depressie, angst, slaapproblemen, migraine en fibromyalgie, en vormt een natuurlijk alternatief voor antidepressiva.",
        "te_gebruiken_bij": "angst, depressies, migraine, spanningshoofdpijn, ADHD, slaapproblemen, fibromyalgie",
        "gebruikt_plantendeel": "Zaden",
        "aanbevolen_combinaties": "Griffonia + Hop (slaapstoornissen), Griffonia + Moederkruid (hoofdpijn en migraine), Griffonia + Avena Sativa (trauma)",
        "niet_te_gebruiken_bij": "zwangerschap, borstvoedingsperiode",
        "categorie_kleur": "",
        "details": "Rijke bron van 5-HTP, precursor van serotonine. Ondersteunt stemming, slaap, pijnbestrijding en neurologisch evenwicht. Natuurlijk alternatief voor antidepressiva, zonder verslavende werking.",
        "afbeelding": "griffonia.jpg",
    },
    {
        "naam": "Groene Thee",
        "botanische_naam": "Camellia sinensis",
        "beschrijving": "Groene Thee wordt gewonnen uit de knoppen en jonge blaadjes van de theestruik, die groeit in de koele, vochtige gebergten van subtropische gebieden. De blaadjes bevatten cafeïne en andere werkzame stoffen die vetverbranding stimuleren en de opname van suikers en vetten verminderen. Groene Thee is effectief bij afslankkuren en vetafbraak en wordt vaak gecombineerd met Javaanse Thee voor extra vochtafdrijving.",
        "te_gebruiken_bij": "vermagering, afslankkuren, overgewicht, zwaarlijvigheid, vetverbranding van vetcellen",
        "gebruikt_plantendeel": "Knop en eerste twee blaadjes van de tak",
        "aanbevolen_combinaties": "Groene Thee + Javaanse Thee (vet afbreken en vocht afdrijven), Groene Thee + Konjac (vet afbreken en honger stillen), Groene Thee + Maté (vet afbreken en vet verbranden)",
        "niet_te_gebruiken_bij": "zwangerschap, borstvoedingsperiode",
        "categorie_kleur": "",
        "details": "Stimuleert vetverbranding en remt suiker- en vetopname. Bevat cafeïne en antioxidanten. Combineert goed met Javaanse Thee, Konjac en Maté voor afslankdoeleinden.",
        "afbeelding": "groene_thee.jpg",
    },
    {
        "naam": "Grote Klis",
        "botanische_naam": "Arctium lappa",
        "beschrijving": "Grote Klis is een tweejarige plant uit Europa met kenmerkende stekelige bloemhoofden. De wortel bevat zuuradionen, polyenen en fenolzuren die ontgiftend, antibacterieel en schimmelwerend werken. Grote Klis wordt ingezet bij huidproblemen zoals acne, mee-eters en puistjes, en ondersteunt de reiniging van lever, nieren en talgklieren. Ook effectief bij ouderdomsdiabetes.",
        "te_gebruiken_bij": "mee-eters, acne, steenpuisten, reiniging talgklieren, suikerziekte (ouderdom), huidzuiverend, bloedzuiverend",
        "gebruikt_plantendeel": "Wortel",
        "aanbevolen_combinaties": "Grote Klis + Biergist (acne & steenpuisten), Grote Klis + Borage-olie (psoriasis), Grote Klis + Artisjok + Paardenbloem (geelzucht)",
        "niet_te_gebruiken_bij": "zwangerschap, borstvoedingsperiode",
        "categorie_kleur": "",
        "details": "Werkt huid- en bloedzuiverend, ondersteunt lever en nieren, verlaagt bloedsuiker. Effectief bij huidproblemen en ouderdomssuiker. Bevat fenolzuren, polyenen en zuuradionen.",
        "afbeelding": "grote_klis.jpg",
    },
    {
        "naam": "Guarana",
        "botanische_naam": "Paullinia cupana",
        "beschrijving": "Guarana is een stimulerende plant uit het Amazonegebied, bekend om zijn zaad dat rijk is aan cafeïne. Het verhoogt de energie, verbetert de concentratie, stimuleert vetverbranding en ondersteunt bij afslankkuren. Guarana wordt vaak ingezet bij vermoeidheid, energietekort en om de fysieke en mentale prestaties te verbeteren.",
        "te_gebruiken_bij": "energietekort, concentratiezwakte, vermoeidheid, afslanken",
        "gebruikt_plantendeel": "Zaad",
        "aanbevolen_combinaties": "Guarana + Ginseng (onmiddellijke oppepper), Guarana + Royal Jelly (chronische vermoeidheid)",
        "niet_te_gebruiken_bij": "zwangerschap, borstvoedingsperiode",
        "categorie_kleur": "",
        "details": "Rijk aan cafeïne. Stimuleert adrenaline-afgifte, verhoogt basismetabolisme en vetverbranding. Geschikt voor afslankdoeleinden en mentale alertheid. Populair in sport- en energiedranken.",
        "afbeelding": "guarana.jpg",
    },
    {
        "naam": "Heermoes",
        "botanische_naam": "Equisetum arvense",
        "beschrijving": "Heermoes, ook wel paardenstaart genoemd, is een niet-bloeiende plant met diepe wortelstokken. Rijk aan siliciumdioxide, ondersteunt het herstel van botten, pezen en kraakbeen. Heermoes stimuleert collageenaanmaak, helpt bij botontkalking en reuma, en is effectief tegen kalknagels. Het is bijzonder nuttig voor sporters en ouderen met bindweefsel- of peesklachten.",
        "te_gebruiken_bij": "osteoporose, botontkalking, botbreuken, bindweefselzwakte, tendinitis, tennisarm, reuma, artritis, slijmbeurstonstekingen, kalknagels",
        "gebruikt_plantendeel": "Bovengronds steriel gedeelte",
        "aanbevolen_combinaties": "Heermoes + Lithothamnium (botontkalking), Heermoes + Boswellia (slijmbeurstonsteking, carpaal tunnel syndroom), Heermoes + Propolis (kalknagels)",
        "niet_te_gebruiken_bij": "zwangerschap, borstvoedingsperiode",
        "categorie_kleur": "",
        "details": "Rijk aan siliciumdioxide (kiezelzuur). Ondersteunt herstel van botten, pezen en nagels. Verbetert collageensynthese en kraakbeenreconstructie. Geschikt voor pees-, bot- en nagelproblemen.",
        "afbeelding": "heermoes.jpg",
    },
    {
        "naam": "Hop",
        "botanische_naam": "Humulus lupulus",
        "beschrijving": "Hop is een klimplant uit Europa en Azië, vooral bekend van het gebruik in bier, maar ook om zijn geneeskrachtige werking. De vrouwelijke hopbellen bevatten vluchtige oliën met een kalmerende werking. Hop wordt gebruikt bij angst, slaapstoornissen, PMS en overgangsklachten. Het bevordert geestelijke rust en hormonale balans, vooral bij vrouwen.",
        "te_gebruiken_bij": "angst, depressies, slaapstoornissen, overactiviteit, overgangsklachten, premenstrueel syndroom",
        "gebruikt_plantendeel": "Kegel",
        "aanbevolen_combinaties": "Hop + Rode Klaver (overgangsklachten), Hop + Fenegriek (borstvergroting), Hop + Griffonia (slaapstoornissen), Hop + Maca (te vroege menopauze)",
        "niet_te_gebruiken_bij": "zwangerschap, borstvoedingsperiode",
        "categorie_kleur": "",
        "details": "Bevat kalmerende vluchtige oliën. Ondersteunt slaap, hormonale balans en gemoedstoestand. Traditioneel gebruikt bij onrust, PMS en overgang. Ook ingezet bij borstvergroting.",
        "afbeelding": "hop.jpg",
    },
    {
        "naam": "Javaanse Thee (Koemis Koetjing)",
        "botanische_naam": "Orthosiphon stamineus",
        "beschrijving": "Javaanse Thee, ook bekend als Koemis Koetjing, is een traditioneel kruid uit Zuidoost-Azië dat in de fytotherapie wordt gebruikt vanwege zijn krachtige vochtafdrijvende werking. De bladeren bevatten flavonen, kalium en vluchtige oliën die de uitscheiding van water en zouten stimuleren. Wordt veel gebruikt bij oedeem en als ondersteuning bij afslankkuren.",
        "te_gebruiken_bij": "vochthoping, oedeem, eliminatie van afvalstoffen, dikke benen, overgewicht door het vasthouden van vocht",
        "gebruikt_plantendeel": "Blad",
        "aanbevolen_combinaties": "Javaanse Thee + Groene Thee (vocht afdrijven en vet afbreken), Javaanse Thee + Maté (vocht afdrijven en vet verbranden)",
        "niet_te_gebruiken_bij": "zwangerschap, borstvoedingsperiode",
        "categorie_kleur": "",
        "details": "Plantaardige plaspil. Stimuleert uitscheiding van vocht en zouten via de nieren. Ideaal bij oedeem, dikke benen en afslankdoeleinden. Versterkt in combinatie met Groene Thee of Maté.",
        "afbeelding": "javaanse_thee.jpg",
    },
    {
        "naam": "Kersensteel",
        "botanische_naam": "Prunus cerasus",
        "beschrijving": "De steeltjes van de zure kers zijn traditioneel gebruikt als vochtafdrijvend middel en worden vandaag de dag gewaardeerd om hun kalmerende werking op de urinewegen. Kersensteel bevordert de urineproductie en helpt bij het afvoeren van overtollig vocht en afvalstoffen. Wordt toegepast bij oedeem, blaasontstekingen en een verminderde urineproductie.",
        "te_gebruiken_bij": "vocht afdrijven, urineweginfecties, blaasontsteking, oedeem, dikke enkels, geringe urineproductie",
        "gebruikt_plantendeel": "Steeltjes van de kers",
        "aanbevolen_combinaties": "Kersensteel + Cranberry (urineweginfecties), Kersensteel + Paardenbloem (nierstenen), Kersensteel + Russische Ginseng (blaas moeilijk leegplassen)",
        "niet_te_gebruiken_bij": "zwangerschap",
        "categorie_kleur": "",
        "details": "Traditioneel vochtafdrijvend middel met kalmerende werking op de urinewegen. Bevordert de urineproductie en voorkomt oedeem. Werkt ondersteunend bij blaasontsteking en nierproblemen.",
        "afbeelding": "kersensteel.jpg",
    },
    {
        "naam": "Konjac",
        "botanische_naam": "Amorphophallus konjac",
        "beschrijving": "Konjac is een plant waarvan de wortel traditioneel in Japan wordt gebruikt. In de fytotherapie staat Konjac bekend als een krachtige hongerstiller. De wortel bevat glucomannaan, een vezel die tot 100 keer zijn gewicht aan water kan opnemen, waardoor een gel in de maag ontstaat die langdurige verzadiging geeft. Konjac ondersteunt bij gewichtsverlies en vermindert de opname van vetten en suikers in de darmen.",
        "te_gebruiken_bij": "afslanken, hongergevoel, snoepzucht, overgewicht, zwaarlijvigheid, snelle verzadiging",
        "gebruikt_plantendeel": "Wortel",
        "aanbevolen_combinaties": "Konjac + Maté (sneller verzadigd gevoel), Konjac + Garcinia (grote eetlust)",
        "niet_te_gebruiken_bij": "zwangerschap, borstvoedingsperiode",
        "categorie_kleur": "",
        "details": "Bevat glucomannaan, een niet-verteerbare, waterbindende vezel. Vormt een volumineuze gel in de maag, onderdrukt het hongergevoel, vermindert vet- en suikeropname. Helpt bij afslankprogramma’s.",
        "afbeelding": "konjac.jpg",
    },
    {
        "naam": "Laksavital",
        "botanische_naam": "Plantago ovata",
        "beschrijving": "Laksavital is een natuurlijk middel op basis van psylliumzaad (vlozaad), rijk aan slijmstoffen. Het vergroot het volume en de hydratatie van de ontlasting en stimuleert op milde wijze de darmperistaltiek zonder kramp of gewenning. Ook heeft het een beschermende werking op de maagwand. Ideaal bij chronische obstipatie en trage darmwerking.",
        "te_gebruiken_bij": "obstipatie (chronisch), trage darmwerking, slechte stoelgang",
        "gebruikt_plantendeel": "Zaadvlies",
        "aanbevolen_combinaties": "Laksavital + Acidophilus (herstel darmflora), Laksavital + Garcinia (afslanken, transporteren vetten)",
        "niet_te_gebruiken_bij": "",
        "categorie_kleur": "",
        "details": "Rijk aan slijmstoffen. Verbetert stoelgang en darmwerking zonder afhankelijkheid. Werkt ook beschermend op de maagwand. Veilig alternatief voor synthetische laxeermiddelen.",
        "afbeelding": "laksavital.jpg",
    },
    {
        "naam": "Levertraanolie",
        "botanische_naam": "Gadus Morhua",
        "beschrijving": "Levertraanolie wordt gewonnen uit de lever van de kabeljauw en is rijk aan vitamine A en D. Het werd traditioneel gebruikt om rachitis (Engelse ziekte) te voorkomen en is tegenwoordig vooral bekend om zijn rol in het ondersteunen van de botaanmaak, het immuunsysteem en de groei bij kinderen. Levertraan helpt bij osteoporose, botbreuken en verhoogt de weerstand.",
        "te_gebruiken_bij": "opgroeiende kinderen, osteoporose, herstel na botbreuken, weerstand",
        "gebruikt_plantendeel": "Verse kabeljauw vislevers",
        "aanbevolen_combinaties": "Levertraanolie + Royal Jelly (opgroeiende kinderen), Levertraanolie + Lithothamnium (osteoporose), Levertraanolie + Heermoes (herstel van botbreuken)",
        "niet_te_gebruiken_bij": "",
        "categorie_kleur": "",
        "details": "Bron van vitamine A en D. Ondersteunt botgroei, weerstand, huid en ogen. Traditioneel gebruikt bij kinderen en ouderen. Vandaag vaak in capsulevorm vanwege de smaak.",
        "afbeelding": "levertraanolie.jpg",
    },
    {
        "naam": "Lijnzaadolie (Omega-3-olie)",
        "botanische_naam": "Linum usitatissimum",
        "beschrijving": "Lijnzaadolie wordt gewonnen uit het zaad van de vlasplant en is bijzonder rijk aan omega-3 vetzuren. Deze essentiële vetzuren ondersteunen de concentratie, het gedrag (zoals bij ADHD), het cholesterolgehalte, de bloeddruk en de gezondheid van huid en ogen. Lijnzaadolie is veelzijdig inzetbaar bij lichamelijke en cognitieve klachten en wordt aanbevolen bij stressgerelateerde en neurologische aandoeningen.",
        "te_gebruiken_bij": "huidaandoeningen, allergieën, droge ogen, ADHD, overactiviteit, te hoog cholesterolgehalte, hoge bloeddruk, stress, humerus­chromie, dyslexie, dyspraxie",
        "gebruikt_plantendeel": "Zaad",
        "aanbevolen_combinaties": "Lijnzaadolie + Bacopa (ADHD), Lijnzaadolie + Cat’s Claw (ziekte van Lyme), Lijnzaadolie + Blauwe Bosbesvrucht (droge ogen, slecht zicht)",
        "niet_te_gebruiken_bij": "zwangerschap, borstvoedingsperiode",
        "categorie_kleur": "",
        "details": "Rijk aan essentiële omega-3 vetzuren. Ondersteunt mentale functies, hart- en vaatgezondheid, huid en ogen. Effectief bij hyperactiviteit, cholesterol en droge ogen. Vervangt ontbrekende vetzuren in het moderne dieet.",
        "afbeelding": "lijnzaadolie.jpg",
    },
    {
        "naam": "Lithothamnium",
        "botanische_naam": "Lithothamnium calcareum",
        "beschrijving": "Lithothamnium is een kalkhoudende alg die rijk is aan calciumcarbonaat, magnesium en oligo-elementen. Het neutraliseert maag- en urinezuren, ondersteunt bij maagpijn, brandend maagzuur, reuma en artrose. Dankzij zijn goed opneembare mineralen helpt Lithothamnium ook bij het versterken van botten en het behouden van een gezond zuur-base evenwicht.",
        "te_gebruiken_bij": "reuma, artrose, artritis, ischias, brandend maagzuur, maagpijn, osteoporose",
        "gebruikt_plantendeel": "Thallus",
        "aanbevolen_combinaties": "Lithothamnium + Duivelsklauw + Duivelsklauw gel (reuma, artritis, jicht), Lithothamnium + Heermoes (botontkalking)",
        "niet_te_gebruiken_bij": "",
        "categorie_kleur": "",
        "details": "Rijk aan calciumcarbonaat en magnesium. Neutraliseert maag- en urinezuren. Plantaardige bron van mineralen, goed opneembaar. Ondersteunt botgezondheid en zuur-base balans.",
        "afbeelding": "lithothamnium.jpg",
    },
    {
        "naam": "Maca",
        "botanische_naam": "Lepidium meyenii",
        "beschrijving": "Maca is een wortelplant uit het Peruaanse Andesgebergte en wordt al sinds de tijd van de Inca’s gebruikt als natuurlijk energie- en libidoverhogend middel. Het ondersteunt seksuele gezondheid, verhoogt de vruchtbaarheid, helpt sportprestaties verbeteren, bevordert herstel na inspanning en verlicht overgangsklachten door het hormonale systeem te balanceren.",
        "te_gebruiken_bij": "vergroot uithoudingsvermogen, helpt (sport) prestaties te verbeteren, libido verhogen, erectiestoornis, vruchtbaarheid (verhogend), verstoorde hormoonbalans, overgangsklachten",
        "gebruikt_plantendeel": "Knol",
        "aanbevolen_combinaties": "Maca + Royal Jelly (vermoeidheid), Maca + Hop (te vroege menopauze)",
        "niet_te_gebruiken_bij": "zwangerschap, borstvoedingsperiode",
        "categorie_kleur": "",
        "details": "Rijk aan vitaminen, mineralen en aminozuren. Verhoogt libido en vruchtbaarheid, ondersteunt hormonale balans en sportprestaties. Inzetbaar bij overgang, vermoeidheid en prestatieherstel.",
        "afbeelding": "maca.jpg",
    },
    {
        "naam": "Maretak",
        "botanische_naam": "Viscum Album",
        "beschrijving": "Maretak is een halfparasitaire struik die groeit op bomen en traditioneel wordt ingezet bij hart- en bloeddrukproblemen. De bladeren en stengels bevatten polyfenolen, lectines en viscotoxines die de bloeddruk reguleren, de hartslag kalmeren en de bloedvaten verwijden. Maretak wordt gebruikt ter ondersteuning van hart- en vaatgezondheid en bij milde hypertensie.",
        "te_gebruiken_bij": "te hoge bloeddruk, hart- en vaatziekten (preventief), aderverkalking, licht verhoogde spanningen in de bloeddruk, het in balans houden van de bloeddruk",
        "gebruikt_plantendeel": "Blad en het stengeltje",
        "aanbevolen_combinaties": "Maretak + Curcuma (bloeddrukschommelingen)",
        "niet_te_gebruiken_bij": "zwangerschap, borstvoedingsperiode",
        "categorie_kleur": "",
        "details": "Werkt bloeddrukverlagend, hartversterkend en vaatverwijdend. Rijk aan polyfenolen, lectines en viscotoxines. Reguleert de hartslag zonder negatieve invloed op circulatie. Wordt vaak tijdelijk ingezet bij milde hypertensie.",
        "afbeelding": "maretak.jpg",
    },
    {
        "naam": "Mariadistel",
        "botanische_naam": "Silybum marianum",
        "beschrijving": "Mariadistel is een Zuid-Europese plant die bekend staat om zijn leverbeschermende werking. De vrucht bevat silymarine, een mengsel van silybine, silydianine en silychristine, dat de levercellen beschermt, galafvoer stimuleert en helpt bij leverherstel. Mariadistel wordt ingezet bij alcoholmisbruik, voedselvergiftiging en ter ondersteuning van de leverfunctie.",
        "te_gebruiken_bij": "alcoholmisbruik, kater, leverreiniging, voedselvergiftiging, bescherming longweefsel",
        "gebruikt_plantendeel": "Vrucht",
        "aanbevolen_combinaties": "Mariadistel + Artisjok (leverproblemen, hepatitis), Mariadistel + Paardenbloem (ontgiften lichaam), Mariadistel + Vitamine D plantaardig (herstellen longweefsel, covid-19)",
        "niet_te_gebruiken_bij": "zwangerschap, borstvoedingsperiode",
        "categorie_kleur": "",
        "details": "Rijk aan silymarine. Ondersteunt leverherstel, galafvoer en detoxificatie. Wordt gebruikt bij leverinsufficiëntie, alcoholgebruik en ter bescherming van long- en leverweefsel. Bewezen ontgiftende werking.",
        "afbeelding": "mariadistel.jpg",
    },
    {
        "naam": "Maté",
        "botanische_naam": "Ilex paraguariensis",
        "beschrijving": "Maté is een populaire Zuid-Amerikaanse theesoort met krachtige opwekkende en afslankende eigenschappen. De bladeren bevatten natuurlijke vetverbranders en suikermetabolisme-regelaars, wat bijdraagt aan effectief gewichtsverlies. Maté ondersteunt bij vetverbranding, verhoogt de energie en helpt bij het verkrijgen van een sneller verzadigd gevoel.",
        "te_gebruiken_bij": "vermageringskuren, afslanken, vetverbrander, overtollige kilo’s",
        "gebruikt_plantendeel": "Blad",
        "aanbevolen_combinaties": "Maté + Garcinia (overgewicht met cellulitis), Maté + Konjac (sneller verzadigd gevoel), Maté + Moederkruid (spanningshoofdpijn)",
        "niet_te_gebruiken_bij": "zwangerschap, borstvoedingsperiode",
        "categorie_kleur": "",
        "details": "Stimuleert vetverbranding en suikerstofwisseling. Ondersteunt afslankkuren, energiebalans en verzadiging. Werkt opwekkend en bevordert mentaal en lichamelijk uithoudingsvermogen.",
        "afbeelding": "mate.jpg",
    },
    {
        "naam": "Melisse (Citroenmelisse)",
        "botanische_naam": "Melissa officinalis",
        "beschrijving": "Melisse, ook wel citroenmelisse genoemd, is een rustgevende plant met een frisse citroengeur. Ze werkt krampwerend op het maag-darmstelsel en ondersteunt de galafscheiding, wat de spijsvertering ten goede komt. Daarnaast heeft melisse een kalmerend effect op het zenuwstelsel en helpt ze bij innerlijke onrust, stress, slapeloosheid en examenstress.",
        "te_gebruiken_bij": "maag- en darmkrampen, spijsverteringsstoornissen, nervositeit, stress, slapeloosheid, angst, depressies, innerlijke onrust, examenstress, plantenkoorts",
        "gebruikt_plantendeel": "Blad",
        "aanbevolen_combinaties": "Melisse + Avena sativa (paniekaanvallen, nachtmerries), Melisse + Artisjok (opgezette maag, moeilijke spijsvertering)",
        "niet_te_gebruiken_bij": "zwangerschap, borstvoedingsperiode",
        "categorie_kleur": "",
        "details": "Krampwerend en kalmerend. Verlicht spijsverteringsklachten en ondersteunt mentale rust. Geschikt bij stress, innerlijke onrust en slaapklachten. Verbetert galafscheiding.",
        "afbeelding": "melisse.jpg",
    },
    {
        "naam": "Meidoorn",
        "botanische_naam": "Crataegus laevigata",
        "beschrijving": "Meidoorn is een krachtig kruid dat traditioneel wordt ingezet bij hart- en vaatproblemen. De bloemknoppen bevatten flavonoïden zoals hyperoside en vitexine die de hartslag reguleren, kransslagaders verwijden en de bloeddruk verlagen. Meidoorn bevordert de doorbloeding van de hartspier en helpt bij herstel na hartproblemen. Het werkt kalmerend bij hartkloppingen en spanningen.",
        "te_gebruiken_bij": "hartkloppingen, hart- en vaatziekten, hartritmestoornissen, pijn op de borst, hoge bloeddruk",
        "gebruikt_plantendeel": "Bloemknop",
        "aanbevolen_combinaties": "Meidoorn + Rhodiola (stress bij volwassenen), Meidoorn + Moederkruid + Maretak (ziekte van Ménière), Meidoorn + Passiebloem (ontwennen slaappillen), Meidoorn + Q10 (hartfalen/hartritmestoornissen)",
        "niet_te_gebruiken_bij": "zwangerschap, borstvoedingsperiode",
        "categorie_kleur": "",
        "details": "Reguleert hartslag en bloeddruk. Verbetert doorbloeding van de hartspier. Ondersteunt het cardiovasculaire systeem bij stress, hartritmestoornissen en hoge bloeddruk. Traditioneel ingezet bij hartzwakte en angstgevoelens.",
        "afbeelding": "meidoorn.jpg",
    },
    {
        "naam": "Pompoenpitolie",
        "botanische_naam": "Cucurbita pepo",
        "beschrijving": "Pompoenpitolie wordt gewonnen uit de zaden van de pompoenplant en staat bekend om zijn ondersteunende werking op de prostaat en urinewegen. De olie is rijk aan sterolen en helpt bij goedaardige prostaatvergroting, verbetert de urinestroom en ondersteunt bij ongewenst urineverlies, ook bij vrouwen met verslapte bekkenbodemspieren.",
        "te_gebruiken_bij": "prostaatvergroting, pijn bij het urineren, nadruppelen van urine, ongewenst urineverlies, blaasontsteking",
        "gebruikt_plantendeel": "Pitten",
        "aanbevolen_combinaties": "Pompoenpitolie + Cranberry (infectie in resturine bij mannen), Pompoenpitolie + Russische Ginseng (verslapping bekkenbodemspieren)",
        "niet_te_gebruiken_bij": "zwangerschap, borstvoedingsperiode",
        "categorie_kleur": "",
        "details": "Rijk aan sterolen. Ondersteunt prostaatgezondheid en bekkenbodemspieren. Bevordert de urinestroom en voorkomt nadruppelen en ongewenst urineverlies. Geschikt voor zowel mannen als vrouwen.",
        "afbeelding": "pompoenpitolie.jpg",
    },
    {
        "naam": "Plantaardige Kool",
        "botanische_naam": "Carbo vegetalis",
        "beschrijving": "Plantaardige Kool wordt verkregen uit verkoolde kokosnootschalen en is een krachtig natuurlijk adsorptiemiddel. Dankzij een zeer poreuze structuur kan het effectief toxines, gassen en bacteriën binden in het spijsverteringskanaal. Het is inzetbaar bij diarree, voedselvergiftiging, opgeblazen gevoel, winderigheid en slechte adem door darmfermentatie.",
        "te_gebruiken_bij": "voedselvergiftiging, diarree, slechte adem, opgeblazen gevoel, winderigheid, mondflora problemen",
        "gebruikt_plantendeel": "Kokosnootschalen",
        "aanbevolen_combinaties": "Plantaardige Kool + Blauwe Bosbesvrucht (diarree), Plantaardige Kool + Venkel (prikkelbare darm)",
        "niet_te_gebruiken_bij": "zwangerschap",
        "categorie_kleur": "",
        "details": "Zeer sterk adsorberend vermogen. Reinigt darmen van toxines en gassen. Effectief bij spijsverteringsklachten, winderigheid en slechte adem. Houd afstand van andere medicatie bij inname vanwege mogelijke interactie.",
        "afbeelding": "plantaardige_kool.jpg",
    },
    {
        "naam": "Passiebloem",
        "botanische_naam": "Passiflora incarnata",
        "beschrijving": "Passiebloem is een sierlijke slingerplant met kalmerende eigenschappen die doorslaapproblemen en slapeloosheid op natuurlijke wijze aanpakt. Het bovengrondse gedeelte bevat flavonoïden en alkaloïden die bijdragen aan ontspanning en een gezonde nachtrust. Het herstelt het slaappatroon zonder verslavende werking en wordt ingezet bij stress, nervositeit en nachtelijk ontwaken.",
        "te_gebruiken_bij": "doorslaapproblemen, slapeloosheid, nervositeit, stress, nachtelijk ontwaken",
        "gebruikt_plantendeel": "Bovengronds gedeelte",
        "aanbevolen_combinaties": "Passiebloem + Meidoorn (ontwennen slaappillen), Passiebloem + Goudpapaver (ongestoorde nachtrust)",
        "niet_te_gebruiken_bij": "zwangerschap, borstvoedingsperiode",
        "categorie_kleur": "",
        "details": "Rustgevend bij slaapproblemen en innerlijke onrust. Bevordert doorslapen zonder gewenning. Ook geschikt voor kinderen. Verbetert nachtrust bij stress en spanning.",
        "afbeelding": "passiebloem.jpg",
    },
    {
        "naam": "Paardenbloem",
        "botanische_naam": "Taraxacum officinalis",
        "beschrijving": "Paardenbloem is een veelvoorkomende plant met krachtige detox-eigenschappen. De wortel werkt vochtafdrijvend, stimuleert de lever en galblaas, en bevordert de uitscheiding van toxines. Door de aanwezigheid van bitterstoffen verhoogt het de galproductie en verbetert het de spijsvertering. Wordt ingezet bij detoxkuren, gal- en nierstenen en voor het stimuleren van de stofwisseling.",
        "te_gebruiken_bij": "opgehoopte toxines, detox, ontgiften van het lichaam, gal- en nierstenen",
        "gebruikt_plantendeel": "Wortel",
        "aanbevolen_combinaties": "Paardenbloem + Mariadistel (ontgiften lichaam), Paardenbloem + Salvia (opgezette buik voor menstruatie), Paardenbloem + Artisjok (psoriasis), Paardenbloem + Artisjok + Grote Klis (geelzucht)",
        "niet_te_gebruiken_bij": "zwangerschap",
        "categorie_kleur": "",
        "details": "Krachtige detoxplant. Stimuleert galproductie en leverwerking. Ondersteunt afvoer van toxines en preventie van gal- en nierstenen. Verbetert spijsvertering en stofwisseling.",
        "afbeelding": "paardenbloem.jpg",
    },
    {
        "naam": "Moederkruid",
        "botanische_naam": "Tanacetum parthenium",
        "beschrijving": "Moederkruid is een traditioneel kruid met een sterke geur en krachtige werking tegen migraine en hoofdpijn. De bloemknoppen bevatten parthenolide, een stof die het vrijkomen van serotonine remt en daardoor migraineaanvallen helpt voorkomen en verzachten. Ook effectief bij oorsuizen (tinnitus) veroorzaakt door uiteenlopende oorzaken zoals infecties of hoge bloeddruk.",
        "te_gebruiken_bij": "hoofdpijn, migraine, voorkomen van migraine, oorsuizen (tinnitus)",
        "gebruikt_plantendeel": "Bloemknop",
        "aanbevolen_combinaties": "Moederkruid + Ginkgo (oorsuizen), Moederkruid + Maté (spanningshoofdpijn), Moederkruid + Teunisbloemolie (premenstruele migraine)",
        "niet_te_gebruiken_bij": "zwangerschap, borstvoedingsperiode, bloedverdunners",
        "categorie_kleur": "",
        "details": "Bevat parthenolide. Preventieve werking tegen migraine en hoofdpijn. Verlicht tinnitusklachten. Niet gebruiken in combinatie met bloedverdunners of tijdens zwangerschap.",
        "afbeelding": "moederkruid.jpg",
    },
    {
        "naam": "Resveratrol",
        "botanische_naam": "Vitis vinifera",
        "beschrijving": "Resveratrol is een krachtig antioxidant dat voorkomt in de schil van blauwe druiven. Het heeft een celbeschermende werking, vertraagt het verouderingsproces en ondersteunt hart- en bloedvaten. Door zijn antioxidatieve werking wordt het veel ingezet bij anti-aging en ter preventie van hart- en vaatziekten.",
        "te_gebruiken_bij": "celveroudering, hoge bloeddruk, cholesterol, veroudering van de huid, hart- en vaatziekten",
        "gebruikt_plantendeel": "Blauwe druiven",
        "aanbevolen_combinaties": "Resveratrol + Lijnzaadolie (Omega-3-olie) (celveroudering vertragen), Resveratrol + Meidoorn (ondersteunen hartfunctie)",
        "niet_te_gebruiken_bij": "zwangerschap, borstvoedingsperiode",
        "categorie_kleur": "",
        "details": "Polyfenol uit druivenschil. Verbetert bloeddruk, beschermt cellen tegen vrije radicalen, ondersteunt hart- en bloedvaten, populair als anti-aging supplement.",
        "afbeelding": "resveratrol.jpg",
    },
    {
        "naam": "Reishi – Shiitake – Maitake",
        "botanische_naam": "Ganoderma lucidum – Lentinus edodes – Grifola frondosa",
        "beschrijving": "Deze medicinale paddenstoelenmix uit de traditionele Chinese en Japanse geneeskunde ondersteunt het immuunsysteem en verhoogt de weerstand. Reishi (Gesteelde Lakzwam) wordt gebruikt als extract, Shiitake is eetbaar en groeit op hardhout, en Maitake (‘eikhaas’) is bekend om zijn antivirale en ontstekingsremmende werking. Geschikt bij chronische vermoeidheid, verzwakt immuunsysteem, en ter ondersteuning tijdens chemokuren.",
        "te_gebruiken_bij": "Immuunsysteem (verzwakt), verlagen bloeddruk, haarverlies en misselijkheid (chemokuur), chronische vermoeidheid (burn-out), burn-out, griep",
        "gebruikt_plantendeel": "Gedroogde paddenstoelen",
        "aanbevolen_combinaties": "Reishi + Shiitake + Maitake + Brandnetel (chemokuur), Reishi + Shiitake + Maitake + Rhodiola (burn-out)",
        "niet_te_gebruiken_bij": "zwangerschap, borstvoedingsperiode",
        "categorie_kleur": "",
        "details": "Mix van drie krachtige paddenstoelen. Stimuleert immuunsysteem, ondersteunt herstel bij chemotherapie en burn-out. Antiviraal, antibacterieel en ontstekingsremmend.",
        "afbeelding": "reishi_shiitake_maitake.jpg",
    },
    {
        "naam": "Q10 (Ubiquinol)",
        "botanische_naam": "Ubiquinol",
        "beschrijving": "Ubiquinol, de biologisch actieve vorm van co-enzym Q10, speelt een essentiële rol in de energieproductie in onze lichaamscellen. Het verbetert de werking van cellen, weefsels en organen, ondersteunt gezond tandvlees, verhoogt de weerstand en helpt bij vermoeidheid en spierklachten, vooral bij gebruik van statines.",
        "te_gebruiken_bij": "bloedend tandvlees, parodontitis, loszittende tanden, vermoeidheid, herstel na ziekte, verminderde weerstand, spierpijn, tintelingen in handen en voeten",
        "gebruikt_plantendeel": "Biologisch actieve vorm van Q10",
        "aanbevolen_combinaties": "Q10 + Rode Gist Rijst (verlaging cholesterol)",
        "niet_te_gebruiken_bij": "",
        "categorie_kleur": "",
        "details": "Ondersteunt bio-energetische processen. Bevordert herstel bij vermoeidheid, verbetert tandvleesconditie, en vermindert statine-gerelateerde spierklachten.",
        "afbeelding": "q10_ubiquinol.jpg",
    },
    {
        "naam": "Propolis",
        "botanische_naam": "Propolis",
        "beschrijving": "Propolis is een harsachtige substantie verzameld door bijen uit knoppen en hars van bomen. Bijen gebruiken het als natuurlijk beschermmiddel tegen bacteriën, virussen en schimmels. Voor mensen werkt het als een natuurlijk antibioticum, rijk aan vitamines en antioxidanten, en wordt vooral ingezet bij winterkwaaltjes en ter versterking van het immuunsysteem.",
        "te_gebruiken_bij": "activering van het afweersysteem, stimulatie van het immuunsysteem, bestrijding bacteriën virussen en schimmels, ontstekingen (keel huidinfecties etc.), kalknagels",
        "gebruikt_plantendeel": "Knoppen en hars van bomen",
        "aanbevolen_combinaties": "Propolis + Echinacea (stimulatie immuunsysteem, herpes), Propolis + Heermoes (kalknagels)",
        "niet_te_gebruiken_bij": "zwangerschap, de periode dat borstvoeding wordt gegeven, allergie voor bijenkorfproducten",
        "categorie_kleur": "",
        "details": "Bevat vluchtige oliën, vitaminen A, B, C, E en sporenelementen. Verhoogt weerstand en werkt antibacterieel, antiviraal en antischimmel.",
        "afbeelding": "propolis.jpg",
    },
    {
        "naam": "Rhodiola",
        "botanische_naam": "Rhodiola rosea",
        "beschrijving": "Rhodiola is een bergplant die groeit op grote hoogte en bekendstaat om zijn adaptogene eigenschappen. Het helpt het lichaam en de geest zich aan te passen aan extreme omstandigheden, voorkomt uitputting en bevordert zowel fysiek als mentaal herstel. Het wordt veel gebruikt in Rusland om de prestaties van soldaten en sporters te verbeteren.",
        "te_gebruiken_bij": "burn-out, prestatiedruk, vermindering energie door onrust of drukke werkzaamheden, verminderd uithoudingsvermogen, geestelijke druk en inspanning, overbelasting van lichaam en geest, kortstondige stress",
        "gebruikt_plantendeel": "Wortel",
        "aanbevolen_combinaties": "Stress bij volwassenen: Rhodiola + Meidoorn, Burn-out: Rhodiola + Russische Ginseng",
        "niet_te_gebruiken_bij": "zwangerschap, de periode dat borstvoeding wordt gegeven",
        "categorie_kleur": "",
        "details": "Rhodiola verhoogt de veerkracht en het uithoudingsvermogen van lichaam en geest, vermindert de impact van stress en bevordert herstel na mentale of fysieke belasting.",
        "afbeelding": "rhodiola.jpg",
    },
    {
        "naam": "Rode Klaver",
        "botanische_naam": "Trifolium pratense",
        "beschrijving": "Rode Klaver is een vaste plant uit de vlinderbloemenfamilie met roze tot rode bloemen. Het is rijk aan isoflavonen (fyto-oestrogenen) die vergelijkbaar zijn met lichaamseigen oestrogenen en kunnen helpen bij overgangsverschijnselen zoals opvliegers, prikkelbaarheid en stemmingswisselingen. Rode Klaver ondersteunt ook preventief bij osteoporose.",
        "te_gebruiken_bij": "opvliegers, prikkelbaarheid, stemmingswisselingen, nachtelijk transpireren, osteoporose (preventief)",
        "gebruikt_plantendeel": "Bloeiende toppen",
        "aanbevolen_combinaties": "Opvliegers: Rode Klaver + Salvia",
        "niet_te_gebruiken_bij": "zwangerschap, de periode dat borstvoeding wordt gegeven",
        "categorie_kleur": "",
        "details": "Rode Klaver bevat fyto-oestrogenen (plantaardige oestrogenen) die het hormonale evenwicht bij vrouwen in de overgang kunnen ondersteunen. Ze werken mild en helpen bij typische overgangsklachten.",
        "afbeelding": "rode_klaver.jpg",
    },
    {
        "naam": "Rode Gist Rijst",
        "botanische_naam": "Monascus purpureus",
        "beschrijving": "Rode Gist Rijst is een traditioneel Chinees voedingssupplement dat wordt verkregen door fermentatie van rijst met de schimmel Monascus purpureus. Het bevat monacoline K, een natuurlijke stof die de aanmaak van cholesterol in de lever remt en daardoor effectief het LDL-cholesterol verlaagt. Het wordt gezien als een natuurlijk alternatief voor statines.",
        "te_gebruiken_bij": "te hoog cholesterolgehalte, te hoge triglyceriden, hart- en vaatziekten",
        "gebruikt_plantendeel": "Gefermenteerde rijstkorrels",
        "aanbevolen_combinaties": "Verlaging cholesterol: Rode Gist Rijst + Q10",
        "niet_te_gebruiken_bij": "zwangerschap, de periode dat borstvoeding wordt gegeven",
        "categorie_kleur": "",
        "details": "Rode Gist Rijst is populair bij mensen die statines slecht verdragen. Grapefruit kan het effect van monacoline K versterken en dient daarom vermeden te worden tijdens gebruik.",
        "afbeelding": "rode_gist_rijst.jpg",
    },
    {
        "naam": "Russische Ginseng (Siberische Ginseng)",
        "botanische_naam": "Eleutherococcus senticosus",
        "beschrijving": "Russische Ginseng is een adaptogeen kruid afkomstig uit Siberië. Het helpt het lichaam zich aan te passen aan fysieke, mentale en emotionele stress en staat bekend om zijn prestatieverhogende en herstellende eigenschappen. Het wordt vaak gebruikt bij geestelijke vermoeidheid, stress en verlaagd libido. Daarnaast ondersteunt het de spierfunctie rond de bekkenbodem.",
        "te_gebruiken_bij": "concentratieverlies, geestelijke vermoeidheid, stress, verlaagd libido, bekkenbodeminstabiliteit",
        "gebruikt_plantendeel": "Wortel",
        "aanbevolen_combinaties": "Ontwikkelen spierkracht: Russische Ginseng + Fenegriek; Bekkenbodeminstabiliteit: Russische Ginseng + Goudpapaver; Burn-out, oververmoeidheid: Russische Ginseng + Avena sativa",
        "niet_te_gebruiken_bij": "zwangerschap, borstvoeding",
        "categorie_kleur": "",
        "details": "Russische Ginseng wordt ingezet bij hoge mentale druk, herstel na ziekte, verminderde prestaties en fysieke uitputting. Het is populair bij sporters, astronauten en mensen die langdurig onder spanning staan.",
        "afbeelding": "russische_ginseng.jpg",
    },
    {
        "naam": "Royal Jelly",
        "botanische_naam": "Royal Jelly",
        "beschrijving": "Royal Jelly, ook wel koninginnegelei genoemd, is een exclusieve bijenproductie die de bijenkoningin voedt. Het is een rijke bron van vitaminen, mineralen, aminozuren en vetzuren. Het versterkt het immuunsysteem, vertraagt veroudering, ondersteunt herstel na ziekte en is ideaal voor kinderen in de groei.",
        "te_gebruiken_bij": "lichamelijke vermoeidheid, kinderen in de groei, gevoeligheid voor veroudering, herstel na ziekte",
        "gebruikt_plantendeel": "Verse voeding voor de bijenkoningin",
        "aanbevolen_combinaties": "Lichamelijke vermoeidheid: Royal Jelly + Ginseng; Onmiddellijke oppepper: Royal Jelly + Guarana; Vermoeidheid: Royal Jelly + Maca; Herstel na ziekte: Royal Jelly + Ashwagandha",
        "niet_te_gebruiken_bij": "astma, bronchitis",
        "categorie_kleur": "",
        "details": "Royal Jelly is een krachtige natuurlijke energiebron die vitaliteit bevordert, het metabolisme stimuleert en cellen beschermt tegen veroudering. Het is met name geschikt voor herstel na fysieke inspanning of ziekte.",
        "afbeelding": "royal_jelly.jpg",
    },
    {
        "naam": "Salvia",
        "botanische_naam": "Salvia officinalis",
        "beschrijving": "Salvia, ook bekend als salie, is een traditioneel kruid uit het Middellandse Zeegebied dat bekendstaat om zijn positieve werking bij hormonale klachten. Het werkt zweetremmend, helpt bij overgangsklachten zoals opvliegers en nachtelijk zweten, en wordt ook ingezet bij andropauze en menstruatieproblemen.",
        "te_gebruiken_bij": "opvliegers, overgangsklachten, nachtelijk transpireren, andropauze, onregelmatige menstruatie, virusinfecties, zweetvoeten",
        "gebruikt_plantendeel": "blad",
        "aanbevolen_combinaties": "Opvliegers: Salvia + Rode Klaver; Opgezette buik door menstruatie: Salvia + Paardenbloem; Onregelmatige menstruatie: Salvia + Teunisbloemolie",
        "niet_te_gebruiken_bij": "zwangerschap, borstvoeding",
        "categorie_kleur": "",
        "details": "Salvia bevat fyto-oestrogenen die helpen bij hormonale klachten. Het is effectief tegen overmatig zweten, ondersteunt bij de overgang (zowel vrouwelijk als mannelijk) en bevordert een regelmatige menstruatiecyclus.",
        "afbeelding": "salvia.jpg",
    },
    {
        "naam": "Saffraan",
        "botanische_naam": "Crocus sativus",
        "beschrijving": "Saffraan is een van de oudste, meest bekende en kostbaarste specerijen ter wereld. Het staat bekend om zijn karakteristieke smaak en kleur, en wordt al eeuwenlang gebruikt in diverse wereldkeukens. In de fytotherapie wordt het ingezet als natuurlijk antidepressivum, vanwege zijn positieve invloed op stemming, angst en stress. De werkzame bestanddelen crocin en safranal ondersteunen de neurotransmitters in de hersenen.",
        "te_gebruiken_bij": "neerslachtigheid, depressie, geestelijke disbalans, angst (aanvallen), stress, stemmingsstoornis, burn-out",
        "gebruikt_plantendeel": "stijlen & stampers",
        "aanbevolen_combinaties": "Burn-out: Saffraan + Rhodiola; Depressie: Saffraan + Griffonia; Angstaanvallen: Saffraan + Goudpapaver",
        "niet_te_gebruiken_bij": "zwangerschap, de periode dat borstvoeding wordt gegeven",
        "categorie_kleur": "",
        "details": "Saffraan staat ook bekend als 'het rode goud' en is bijzonder effectief bij mentale vermoeidheid en emotionele instabiliteit. Het helpt om stress en angsten te verminderen, bevordert een positieve stemming, en draagt bij aan celbescherming tegen oxidatieve stress. De werking is voelbaar na 6 weken, met optimaal resultaat na 8 weken.",
        "afbeelding": "saffraan.jpg",
    },
    {
        "naam": "Spirulina",
        "botanische_naam": "Spirulina maxima",
        "beschrijving": "Spirulina is een blauwgroene alg die bekendstaat als een superfood. Ze groeit van nature in tropische en subtropische wateren, maar wordt tegenwoordig ook gekweekt in aquaculturen. Spirulina is bijzonder rijk aan eiwitten, bevat alle essentiële aminozuren en voorziet het lichaam langdurig van energie. Het is een uitstekende bron van chlorofyl en ijzer en draagt bij aan celregeneratie en het vertragen van verouderingsprocessen.",
        "te_gebruiken_bij": "vitaliteit (gebrek aan), lage energieniveaus, vermoeidheid, herstel na ziekte, diabetes type 2",
        "gebruikt_plantendeel": "alg",
        "aanbevolen_combinaties": "Herstel na ziekte: Spirulina + Royal Jelly; Hooikoorts: Spirulina + Weegbree; Aanvulling dieet veganisten: Spirulina + Biergist",
        "niet_te_gebruiken_bij": "zwangerschap",
        "categorie_kleur": "",
        "details": "Spirulina bestaat voor 60–70% uit eiwit met alle essentiële aminozuren. Het reguleert de bloedsuikerspiegel dankzij het pigment phycocyanine en vertraagt het fysieke en mentale verouderingsproces door stimulatie van de aanmaak van rode bloedcellen en verbeterde celademhaling.",
        "afbeelding": "spirulina.jpg",
    },
    {
        "naam": "Sint Janskruid",
        "botanische_naam": "Hypericum perforatum",
        "beschrijving": "Sint Janskruid is een in Europa veel voorkomende plant die bloeit rond de langste dag van het jaar. De plant staat bekend om haar positieve invloed op de gemoedstoestand. Het wordt ingezet bij neerslachtigheid, innerlijke onrust en hormonale disbalans na bevalling of tijdens de overgang. In tegenstelling tot synthetische antidepressiva kent Sint Janskruid geen gewenning.",
        "te_gebruiken_bij": "depressiviteit, innerlijke onrust, overspannenheid, neerslachtigheid, sombere stemming, prikkelbaarheid",
        "gebruikt_plantendeel": "bloemknop",
        "aanbevolen_combinaties": "Whiplash: Sint Janskruid + Ginkgo; Gespannen + migraine: Sint Janskruid + Moederkruid",
        "niet_te_gebruiken_bij": "zwangerschap, de periode dat borstvoeding wordt gegeven",
        "categorie_kleur": "",
        "details": "Sint Janskruid is een natuurlijk antidepressivum dat zonder bijwerkingen langdurig gebruikt kan worden. Een kuur van 2–3 maanden geeft het beste resultaat. Bij hoge doseringen en zonlicht kan het overgevoeligheid veroorzaken bij mensen met een lichte huid.",
        "afbeelding": "sint_janskruid.jpg",
    },
    {
        "naam": "Valeriaan",
        "botanische_naam": "Valeriana officinalis",
        "beschrijving": "Valeriaan is een vaste plant die in Europa voorkomt, vooral op vochtige gronden langs wateroevers. De wortel bevat rustgevende bestanddelen zoals vluchtige olie en valepotriaten, die effectief zijn bij nervositeit, stress en slaapproblemen. Het middel veroorzaakt geen gewenning of versuffing en is veilig te gebruiken, zelfs bij examenstress.",
        "te_gebruiken_bij": "nervositeit, stress, slaapproblemen, examenstress, tabaksverslaving",
        "gebruikt_plantendeel": "wortel",
        "aanbevolen_combinaties": "Inslapproblemen: Valeriaan + Goudpapaver; Stoppen met roken: Valeriaan + Guarana",
        "niet_te_gebruiken_bij": "zwangerschap, de periode dat borstvoeding wordt gegeven",
        "categorie_kleur": "",
        "details": "Valeriaan kan veilig gebruikt worden bij stressvolle situaties, zoals examens, zonder invloed op het reactievermogen. Het wordt ook ingezet bij stoppen met roken vanwege het kalmerende effect. Vermijd tincturen met alcohol als je nog moet rijden.",
        "afbeelding": "valeriaan.jpg",
    },
    {
        "naam": "Teunisbloemolie",
        "botanische_naam": "Oenothera biennis",
        "beschrijving": "Teunisbloemolie wordt gewonnen uit de zaden van de teunisbloem, een plant die in de avond grote gele bloemen opent. De olie is rijk aan linolzuur en gammalinoleenzuur en ondersteunt het hormonale evenwicht tijdens de tweede helft van de menstruele cyclus. Het is effectief bij menstruatieklachten en premenstrueel syndroom (PMS).",
        "te_gebruiken_bij": "menstruatieklachten, premenstrueel syndroom (PMS), gespannen borsten, buikpijn",
        "gebruikt_plantendeel": "zaad",
        "aanbevolen_combinaties": "Droge huid: Teunisbloemolie + Borage-olie; Onregelmatige menstruatie: Teunisbloemolie + Salvia; Premenstruele migraine: Teunisbloemolie + Moederkruid",
        "niet_te_gebruiken_bij": "zwangerschap, de periode dat borstvoeding wordt gegeven",
        "categorie_kleur": "",
        "details": "Teunisbloemolie ondersteunt vrouwen tijdens de tweede helft van de cyclus en helpt bij typische PMS-symptomen zoals buikpijn, gespannen borsten en stemmingswisselingen. De olie wordt verkregen via koude persing en bevat waardevolle vetzuren voor hormonale balans.",
        "afbeelding": "teunisbloemolie.jpg",
    },
    {
        "naam": "Venkel",
        "botanische_naam": "Foeniculum vulgare",
        "beschrijving": "Venkel is een plant uit het Middellandse Zeegebied en staat bekend om zijn anijsachtige geur en smaak. De vrucht bevat vluchtige olie met krampwerende eigenschappen en wordt ingezet bij spijsverteringsproblemen. Venkel is effectief bij winderigheid, opgeblazen gevoel en maag-darmkrampen.",
        "te_gebruiken_bij": "maag-darmkramp, winderigheid, opgeblazen gevoel, maagpijn, buikpijn, onvoldoende borstvoeding",
        "gebruikt_plantendeel": "vrucht",
        "aanbevolen_combinaties": "Prikkelbare Darm: Venkel + Plantaardige Kool; Misselijkheid: Venkel + Gember; Nerveuze buikklachten: Venkel + Hop",
        "niet_te_gebruiken_bij": "zwangerschap, de periode dat borstvoeding wordt gegeven",
        "categorie_kleur": "",
        "details": "Venkel ondersteunt een gezonde spijsvertering en helpt bij gasvorming en darmkrampen. Het wordt ook traditioneel gebruikt om de melkproductie te bevorderen, hoewel Fenegriek tegenwoordig vaker wordt aanbevolen voor dit doel.",
        "afbeelding": "venkel.jpg",
    },
    {
        "naam": "Weegbree",
        "botanische_naam": "Plantago major",
        "beschrijving": "Weegbree is een tredplant die veel voorkomt op paden in Europa. Het blad bevat aucuboside, een stof met jeukstillende en ontstekingsremmende eigenschappen. Weegbree wordt ingezet bij allergieën, huidaandoeningen met jeuk, hooikoorts en luchtwegaandoeningen zoals astma en bronchitis.",
        "te_gebruiken_bij": "hooikoorts, jeuk, huisstofmijtallergie, allergie, huidproblemen, astma, bronchitis",
        "gebruikt_plantendeel": "blad",
        "aanbevolen_combinaties": "Gordelroos: Weegbree + Cat’s Claw",
        "niet_te_gebruiken_bij": "zwangerschap, de periode dat borstvoeding wordt gegeven",
        "categorie_kleur": "",
        "details": "Weegbree helpt effectief bij het bestrijden van hooikoorts en allergische reacties. Dankzij zijn slijmoplossende werking is het ook geschikt voor luchtwegproblemen. Preventief gebruik tijdens het pollenseizoen kan klachten voorkomen.",
        "afbeelding": "weegbree.jpg",
    },
    {
        "naam": "Vrouwenmantel",
        "botanische_naam": "Alchemilla vulgaris",
        "beschrijving": "Vrouwenmantel ontleent haar naam aan de mantelvormige bladeren die lijken op de zachte binnenkant van de baarmoeder. De plant heeft een samentrekkende werking door het hoge tanninegehalte en ondersteunt de baarmoeder direct na de bevalling. Het kruid wordt traditioneel ingezet bij vrouwelijke ongemakken zoals menstruatiepijn, witte vloed en hormonale disbalans.",
        "te_gebruiken_bij": "baarmoederverzakking, menstruatiepijn, PMS, witte vloed, overmatige menstruatie",
        "gebruikt_plantendeel": "blad",
        "aanbevolen_combinaties": "Vaginale ontsteking: Vrouwenmantel + Canadese Geelwortel",
        "niet_te_gebruiken_bij": "zwangerschap",
        "categorie_kleur": "",
        "details": "Vrouwenmantel reguleert de menstruatiecyclus en verlicht klachten zoals pijn en overvloedige of juist te zwakke menstruatie. Het ondersteunt ook bij hormonale veranderingen en wordt preventief ingezet na een bevalling om de baarmoeder te herstellen.",
        "afbeelding": "vrouwenmantel.jpg",
    },
    {
        "naam": "Vitamine D3 (plantaardig)",
        "botanische_naam": "Korstmos (lichen)",
        "beschrijving": "Vitamine D3 uit korstmos is een volledig plantaardig alternatief voor de dierlijke vorm en bevat de goed opneembare cholecalciferol D3. Korstmos is een unieke symbiose tussen een schimmel en een alg en groeit onder andere in het Noordpoolgebied. Deze plantaardige vitamine D3 is essentieel voor mensen die weinig zonlicht krijgen of bewust plantaardig leven.",
        "te_gebruiken_bij": "botontkalking, osteoporose, botbreuken, zwakte (gebrek aan), spierzwakte, immuunsysteem (verzwakt), weerstand, Covid-19, ziekte van Pfeiffer, ziekte van Crohn, ziekte van Parkinson, ziekte van Lyme, ziekte van Sjögren, ziekte van Hirschsprung, prikkelbare darm syndroom",
        "gebruikt_plantendeel": "schimmel en alg",
        "aanbevolen_combinaties": "Preventie klachten Covid-19: Vitamine D3 plantaardig + Resveratrol; Verbetering darmmicrobioom: Vitamine D3 plantaardig + Acidophilus; Versterken immuunsysteem: Vitamine D3 plantaardig + Lijnzaadolie (Omega-3 olie); Ziekte van Pfeiffer: Vitamine D3 plantaardig + Cat’s Claw; Ziekte van Crohn: Vitamine D3 plantaardig + Boswellia en/of Curcuma",
        "niet_te_gebruiken_bij": "",
        "categorie_kleur": "",
        "details": "Vitamine D3 is essentieel voor calciumopname, sterke botten, tanden en een goed werkend immuunsysteem. Voor mensen met weinig zonlicht of een plantaardig dieet is suppletie noodzakelijk. Uit onderzoek blijkt dat het immuunsysteem sterker functioneert bij een goed vitamine D-niveau, wat belangrijk is bij o.a. Covid-19 en chronische aandoeningen.",
        "afbeelding": "vitamine_d3_plantaardig.jpg",
    },
    {
        "naam": "Zaagbladpalm",
        "botanische_naam": "Serenoa repens",
        "beschrijving": "De Zaagbladpalm is een palmachtige plant afkomstig uit het Zuidoosten van de Verenigde Staten, Zuid-Europa en Noord-Afrika. De bessen van de Zaagbladpalm worden traditioneel ingezet bij typische mannenkwalen zoals prostaatvergroting, verminderd libido, impotentie en kaalheid.",
        "te_gebruiken_bij": "haaruitval, kaalheid (mannen), nycturie (nachtelijk plassen), prostaatvergroting, incontinentie, moeilijk plassen, impotentie, zin in sex",
        "gebruikt_plantendeel": "bes",
        "aanbevolen_combinaties": "Haaruitval mannen: Zaagbladpalm + Biergist; Prostaatvergroting: Zaagbladpalm + Pompoenpitolie; Impotentie: Zaagbladpalm + Ashwagandha",
        "niet_te_gebruiken_bij": "zwangerschap, de periode dat borstvoeding wordt gegeven",
        "categorie_kleur": "",
        "details": "Zaagbladpalm werkt ondersteunend bij het voorkomen van haaruitval door het blokkeren van het hormoon DHT, dat bijdraagt aan kaalheid. Daarnaast verhoogt het het testosteronniveau op natuurlijke wijze, wat gunstig is voor libido en erectieproblemen. Ook bij prostaatvergroting en plasproblemen biedt het verlichting.",
        "afbeelding": "zaagbladpalm.jpg",
    },
]
